# Generated by Django 2.1.7 on 2021-06-08 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semin', '0400_auto_20210608_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('SEMIN', 'SEMIN'), ('SALUD PARA TODOS', 'SALUD PARA TODOS')], max_length=45, null=True)),
                ('folio', models.CharField(max_length=90, null=True)),
                ('numero_solicitudes', models.IntegerField(null=True)),
                ('paciente', models.CharField(max_length=90, null=True)),
                ('expediente', models.CharField(max_length=90, null=True)),
                ('date', models.DateField(null=True)),
                ('tipo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia electrónica', 'Transferencia electrónica'), ('Tarjeta de crédito', 'Tarjeta de crédito'), ('Tarjeta de debito', 'Tarjeta de debito')], max_length=45, null=True)),
                ('convenio', models.CharField(max_length=90, null=True)),
                ('importe', models.IntegerField(null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Semin - Efectivo en Caja',
            },
        ),
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90, null=True)),
                ('apellido_paterno', models.CharField(max_length=45, null=True)),
                ('apellido_materno', models.CharField(max_length=45, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('sexo', models.CharField(choices=[('masculino', 'masculino'), ('femenino', 'femenino')], max_length=9, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=45, null=True, unique=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Semin - Cajero',
            },
        ),
        migrations.CreateModel(
            name='MontoInicialCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('SEMIN', 'SEMIN'), ('SALUD PARA TODOS', 'SALUD PARA TODOS')], max_length=45, null=True)),
                ('monto_inicial', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
                ('cajero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel_data.Cajero')),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Sucursal')),
            ],
            options={
                'verbose_name_plural': 'Semin - Efectivo Inicial en Caja',
            },
        ),
        migrations.CreateModel(
            name='VentaDespartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('SEMIN', 'SEMIN'), ('SALUD PARA TODOS', 'SALUD PARA TODOS')], max_length=45, null=True)),
                ('departamento', models.CharField(max_length=45, null=True)),
                ('numero_estudios', models.IntegerField(null=True)),
                ('liquidado', models.BooleanField(null=True)),
                ('importe', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
                ('date', models.DateField(null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Sucursal')),
            ],
            options={
                'verbose_name_plural': 'Semin - Ventas por Departamento',
            },
        ),
        migrations.CreateModel(
            name='VentaEstudios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresaa', models.CharField(choices=[('SEMIN', 'SEMIN'), ('SALUD PARA TODOS', 'SALUD PARA TODOS')], max_length=45, null=True)),
                ('estudio', models.CharField(choices=[('Analisis Sanguineos', 'Analisis Sanguineos'), ('Analisis Clinicos', 'Analisis Clinicos'), ('Ultrasonografia', 'Ultrasonografia'), ('Ultrasonografia Doppler', 'Ultrasonografia Doppler'), ('Rayos X', 'Rayos X'), ('Rayos X Contrastados', 'Rayos X Contrastados'), ('Mastografia', 'Mastografia'), ('Papanicolau', 'Papanicolau'), ('Tomografia', 'Tomografia'), ('Tomografia Contrastada', 'Tomografia Contrastada'), ('Resonancia Magnetica', 'Resonancia Magnetica'), ('Resonancia Magnetica Contrastada', 'Resonancia Magnetica Contrastada'), ('Colposcopia', 'Colposcopia'), ('Densitometria', 'Densitometria'), ('Audiologia', 'Audiologia'), ('Espirometria', 'Espirometria'), ('Patologia', 'Patologia'), ('Consulta', 'Consulta'), ('Ginecologia', 'Ginecologia'), ('Cardiologia', 'Cardiologia'), ('Rehabilitacion', 'Rehabilitacion'), ('Cirugia', 'Cirugia'), ('Covid', 'Covid')], max_length=45, null=True)),
                ('numero_estudios', models.IntegerField(null=True)),
                ('liquidado', models.BooleanField(null=True)),
                ('tipo', models.CharField(choices=[('PARTICULAR', 'PARTICULAR'), ('EMPRESA', 'EMPRESA')], max_length=45, null=True)),
                ('importe', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
                ('date', models.DateField(null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Sucursal')),
            ],
            options={
                'verbose_name_plural': 'Semin - Ventas por Estudios',
            },
        ),
        migrations.AddField(
            model_name='caja',
            name='cajero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel_data.Cajero'),
        ),
        migrations.AddField(
            model_name='caja',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Sucursal'),
        ),
    ]
