# Generated by Django 2.1.7 on 2021-06-08 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventaestudios',
            old_name='empresaa',
            new_name='empresa',
        ),
    ]
