# Generated by Django 2.1.7 on 2021-06-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_data', '0003_ventadespartamento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='empresa',
            field=models.CharField(choices=[('semin', 'semin'), ('salud para todos', 'salud para todos')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='montoinicialcaja',
            name='empresa',
            field=models.CharField(choices=[('semin', 'semin'), ('salud para todos', 'salud para todos')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='ventadespartamento',
            name='empresa',
            field=models.CharField(choices=[('semin', 'semin'), ('salud para todos', 'salud para todos')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='ventadespartamento',
            name='tipo',
            field=models.CharField(choices=[('particular', 'particular'), ('empresa', 'empresa')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='ventaestudios',
            name='empresa',
            field=models.CharField(choices=[('semin', 'semin'), ('salud para todos', 'salud para todos')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='ventaestudios',
            name='tipo',
            field=models.CharField(choices=[('particular', 'particular'), ('empresa', 'empresa')], max_length=45, null=True),
        ),
    ]
