# Generated by Django 2.1.7 on 2021-06-15 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0401_auto_20210615_1230'),
        ('panel_data', '0004_auto_20210608_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='AperturaCierreCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.IntegerField(null=True)),
                ('hora_inicio', models.TimeField(null=True)),
                ('monto_final', models.IntegerField(null=True)),
                ('hora_final', models.TimeField(null=True)),
                ('date', models.DateField(null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
                ('cajero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel_data.Cajero')),
            ],
            options={
                'verbose_name_plural': 'Semin - Efectivo Inicial en Caja',
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('semin', 'semin'), ('salud para todos', 'salud para todos')], max_length=45, null=True)),
                ('numero_solicitudes', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('tipo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia electrónica', 'Transferencia electrónica'), ('Tarjeta de crédito', 'Tarjeta de crédito'), ('Tarjeta de debito', 'Tarjeta de debito')], max_length=45, null=True)),
                ('convenio', models.CharField(max_length=90, null=True)),
                ('importe', models.IntegerField(null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
                ('caja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel_data.AperturaCierreCaja')),
                ('cajero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel_data.Cajero')),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Sucursal')),
            ],
            options={
                'verbose_name_plural': 'Semin - Efectivo en Caja',
            },
        ),
        migrations.RemoveField(
            model_name='caja',
            name='cajero',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='montoinicialcaja',
            name='cajero',
        ),
        migrations.RemoveField(
            model_name='montoinicialcaja',
            name='sucursal',
        ),
        migrations.AlterField(
            model_name='ventaestudios',
            name='estudio',
            field=models.CharField(choices=[('Analisis Sanguineos', 'Analisis Sanguineos'), ('Analisis Clinicos', 'Analisis Clinicos'), ('Ultrasonografia', 'Ultrasonografia'), ('Ultrasonografia Doppler', 'Ultrasonografia Doppler'), ('Rayos X', 'Rayos X'), ('Rayos X Contrastados', 'Rayos X Contrastados'), ('Mastografia', 'Mastografia'), ('Papanicolau', 'Papanicolau'), ('Tomografia', 'Tomografia'), ('Tomografia Contrastada', 'Tomografia Contrastada'), ('Resonancia Magnetica', 'Resonancia Magnetica'), ('Resonancia Magnetica Contrastada', 'Resonancia Magnetica Contrastada'), ('Colposcopia', 'Colposcopia'), ('Densitometria', 'Densitometria'), ('Audiologia', 'Audiologia'), ('Espirometria', 'Espirometria'), ('Patologia', 'Patologia'), ('Consulta', 'Consulta'), ('Ginecologia', 'Ginecologia'), ('Cardiologia', 'Cardiologia'), ('Cirugia', 'Cirugia'), ('Covid', 'Covid')], max_length=45, null=True),
        ),
        migrations.DeleteModel(
            name='Caja',
        ),
        migrations.DeleteModel(
            name='MontoInicialCaja',
        ),
    ]
