# Generated by Django 2.1.7 on 2021-06-15 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel_data', '0005_auto_20210615_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajeroOperador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90, null=True)),
                ('apellido_paterno', models.CharField(max_length=45, null=True)),
                ('apellido_materno', models.CharField(max_length=45, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('sexo', models.CharField(choices=[('masculino', 'masculino'), ('femenino', 'femenino')], max_length=9, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=45, null=True, unique=True)),
                ('hora_entrada', models.TimeField(null=True)),
                ('hora_salida', models.TimeField(null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Semin - Cajero Operador',
            },
        ),
        migrations.AlterModelOptions(
            name='aperturacierrecaja',
            options={'verbose_name_plural': 'Panel Data - Apartura de caja'},
        ),
        migrations.AlterModelOptions(
            name='movimientos',
            options={'verbose_name_plural': 'Panel Data - Movimientos en caja'},
        ),
        migrations.AlterField(
            model_name='aperturacierrecaja',
            name='cajero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel_data.CajeroOperador'),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='cajero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel_data.CajeroOperador'),
        ),
        migrations.DeleteModel(
            name='Cajero',
        ),
    ]
