# Generated by Django 2.1.7 on 2021-06-15 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_data', '0008_auto_20210615_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientos',
            old_name='importe',
            new_name='total',
        ),
    ]
