# Generated by Django 2.1.7 on 2021-06-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_data', '0011_movimientos_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
