# Generated by Django 2.1.7 on 2021-06-16 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0401_auto_20210615_1230'),
        ('panel_data', '0012_auto_20210616_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajerooperador',
            name='empresa',
            field=models.CharField(choices=[('semin', 'semin'), ('salud para todos', 'salud para todos')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='cajerooperador',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Sucursal'),
        ),
    ]
