# Generated by Django 2.1.7 on 2021-06-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_data', '0013_auto_20210616_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientos',
            old_name='caja',
            new_name='movimientos',
        ),
    ]
