# Generated by Django 2.1.7 on 2021-06-16 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_data', '0014_auto_20210616_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientos',
            old_name='movimientos',
            new_name='apertura_cierre',
        ),
    ]
