# Generated by Django 2.1.7 on 2021-06-16 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_data', '0015_auto_20210616_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cajerooperador',
            old_name='cajero',
            new_name='cajero_empleado',
        ),
    ]
