# Generated by Django 2.1.7 on 2021-06-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_data', '0016_auto_20210616_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos',
            name='date',
        ),
    ]
