# Generated by Django 2.1.7 on 2021-06-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_data', '0017_remove_movimientos_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadespartamento',
            name='area',
            field=models.CharField(choices=[('Laboratorio', 'Laboratorio'), ('Imagenologia', 'Imagenologia')], max_length=45, null=True),
        ),
    ]
