# Generated by Django 2.1.7 on 2021-06-21 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0401_auto_20210615_1230'),
        ('panel_data', '0018_ventadespartamento_area'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VentaDespartamento',
            new_name='VentaDespartamentoArea',
        ),
    ]
