# Generated by Django 2.1.7 on 2021-06-23 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0401_auto_20210615_1230'),
        ('panel_data', '0019_auto_20210621_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('semin', 'semin'), ('salud para todos', 'salud para todos')], max_length=45, null=True)),
                ('tipo_devolucion', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia electrónica', 'Transferencia electrónica'), ('Tarjeta de crédito', 'Tarjeta de crédito'), ('Tarjeta de debito', 'Tarjeta de debito')], max_length=45, null=True)),
                ('total', models.FloatField(null=True)),
                ('date', models.DateField(null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
                ('cajero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel_data.CajeroOperador')),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Sucursal')),
            ],
            options={
                'verbose_name_plural': 'Panel Data - Devoluciones',
            },
        ),
    ]
