# Generated by Django 2.1.7 on 2021-06-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_data', '0020_devoluciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoluciones',
            name='tipo_devolucion',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia electronica', 'Transferencia electronica'), ('Tarjeta de credito', 'Tarjeta de credito'), ('Tarjeta de debito', 'Tarjeta de debito')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='tipo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia electronica', 'Transferencia electronica'), ('Tarjeta de credito', 'Tarjeta de credito'), ('Tarjeta de debito', 'Tarjeta de debito')], max_length=45, null=True),
        ),
    ]
