# Generated by Django 2.1.7 on 2021-06-29 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0401_auto_20210615_1230'),
        ('panel_data', '0024_auto_20210629_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdminPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
                ('administrador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Empleado')),
            ],
            options={
                'verbose_name_plural': 'Panel Data - Administrador Auditor',
            },
        ),
    ]
