# Generated by Django 2.1.7 on 2021-06-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_data', '0025_useradminpanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradminpanel',
            name='apellido_materno',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='useradminpanel',
            name='apellido_paterno',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='useradminpanel',
            name='email',
            field=models.EmailField(blank=True, max_length=45, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='useradminpanel',
            name='nombre',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='useradminpanel',
            name='puesto',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='useradminpanel',
            name='administrador',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
