# Generated by Django 2.1.7 on 2021-06-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_data', '0027_auto_20210629_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylogin',
            name='apellido_materno',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='activitylogin',
            name='apellido_paterno',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
