# Generated by Django 2.1.7 on 2021-06-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_data', '0028_auto_20210629_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylogin',
            name='action',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
