# Generated by Django 2.1.7 on 2021-06-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_data', '0029_activitylogin_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityviews',
            name='apellido_materno',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='activityviews',
            name='apellido_paterno',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='activityviews',
            name='respuesta',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='activityviews',
            name='consulta',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
