# Generated by Django 2.1.7 on 2021-06-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_data', '0030_auto_20210630_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityviews',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
