# Generated by Django 2.1.7 on 2021-06-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_data', '0032_remove_activityviews_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityviews',
            name='datos',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
