# Generated by Django 2.1.7 on 2021-07-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_data', '0034_useradmin_userpermisos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermisos',
            name='usuario',
        ),
        migrations.AddField(
            model_name='useradmin',
            name='corte_caja',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='devoluciones',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='tipos_pagos',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='venta_areas',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='venta_departamentos',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='venta_estudios',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='venta_sucursal',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='venta_tolal',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.DeleteModel(
            name='UserPermisos',
        ),
    ]
