# Generated by Django 2.1.7 on 2021-07-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_data', '0035_auto_20210705_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradmin',
            name='cambio_estudio',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
