# Generated by Django 2.1.7 on 2021-07-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_data', '0036_useradmin_cambio_estudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradminpanel',
            name='cambio_estudio',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='useradminpanel',
            name='corte_caja',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='useradminpanel',
            name='devoluciones',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='useradminpanel',
            name='tipos_pagos',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='useradminpanel',
            name='venta_areas',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='useradminpanel',
            name='venta_departamentos',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='useradminpanel',
            name='venta_estudios',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='useradminpanel',
            name='venta_sucursal',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='useradminpanel',
            name='venta_tolal',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
