# Generated by Django 2.1.7 on 2021-07-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_data', '0038_auto_20210707_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentasTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('semin', 'semin'), ('salud para todos', 'salud para todos')], max_length=45, null=True)),
                ('date', models.DateField(null=True)),
                ('total', models.FloatField(null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Panel Data - Ventas totales por empresa',
            },
        ),
    ]
