# Generated by Django 2.1.7 on 2020-12-12 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semin', '0314_loginclientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionEstudioDicom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudios_estudios', to='semin.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='EstudioDicom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorio_paciente', models.CharField(max_length=800)),
                ('tipo_estudio', models.CharField(blank=True, choices=[('Analisis Sanguineos', 'Analisis Sanguineos'), ('Analisis Clinicos', 'Analisis Clinicos'), ('Ultrasonografia', 'Ultrasonografia'), ('Ultrasonografia Doppler', 'Ultrasonografia Doppler'), ('Rayos X', 'Rayos X'), ('Rayos X Contrastados', 'Rayos X Contrastados'), ('Mastografia', 'Mastografia'), ('Papanicolau', 'Papanicolau'), ('Tomografia', 'Tomografia'), ('Tomografia Contrastada', 'Tomografia Contrastada'), ('Resonancia Magnetica', 'Resonancia Magnetica'), ('Resonancia Magnetica Contrastada', 'Resonancia Magnetica Contrastada'), ('Colposcopia', 'Colposcopia'), ('Densitometria', 'Densitometria'), ('Audiologia', 'Audiologia'), ('Espirometria', 'Espirometria'), ('Patologia', 'Patologia'), ('Consulta', 'Consulta'), ('Ginecologia', 'Ginecologia'), ('Cardiologia', 'Cardiologia'), ('Rehabilitacion', 'Rehabilitacion')], max_length=100, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Paciente')),
            ],
        ),
        migrations.AddField(
            model_name='actualizacionestudiodicom',
            name='estudio_dicom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualizaciones', to='panel_radiologos.EstudioDicom'),
        ),
    ]
