# Generated by Django 2.1.7 on 2020-12-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_radiologos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiodicom',
            name='interpretado',
            field=models.BooleanField(default=False),
        ),
    ]
