# Generated by Django 2.1.7 on 2021-01-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_radiologos', '0002_estudiodicom_interpretado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicoSemin', models.BooleanField(blank=True, default=False)),
                ('verificado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO')], default='PENDIENTE', max_length=11, null=True)),
                ('nombre', models.CharField(max_length=90, null=True)),
                ('apellido_paterno', models.CharField(max_length=45, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=45, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/doctores')),
                ('cedula', models.CharField(blank=True, max_length=10, null=True)),
                ('especialidad', models.CharField(choices=[('Medicina General', 'Medicina General'), ('Medicina Interna', 'Medicina Interna'), ('Cirugia', 'Cirugía'), ('Endocrinologia', 'Endocrinología'), ('Ginecologia', 'Ginecología'), ('Nefrologia', 'Nefrología'), ('Neurocirugia', 'Neurocirugía'), ('Neurologia', 'Neurología'), ('Pediatria', 'Pediatría'), ('Traumatologia y Ortopedia', 'Traumatología y Ortopedia'), ('Urologia', 'Urología')], max_length=30, null=True)),
                ('subespecialidad', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('CDMX', 'CDMX'), ('Chihuahua', 'Chihuahua'), ('Chiapas', 'Chiapas'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('México', 'México'), ('Michoacán', 'Michoacán'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Ro', 'Quintana Ro'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], max_length=20, null=True)),
                ('estatusConexion', models.CharField(blank=True, choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], max_length=10, null=True)),
                ('ultimaConexion', models.DateTimeField(blank=True, null=True)),
                ('room', models.CharField(blank=True, max_length=60, null=True)),
                ('ranking', models.IntegerField(default=500, null=True)),
                ('estrellas', models.IntegerField(default=5, null=True)),
                ('estrellasArray', models.CharField(blank=True, max_length=100, null=True)),
                ('caducidad', models.DateField(null=True)),
                ('sexo', models.CharField(blank=True, choices=[('masculino', 'masculino'), ('femenino', 'femenino')], max_length=9, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('telefono', models.IntegerField(null=True)),
                ('calle', models.CharField(blank=True, max_length=90, null=True)),
                ('colonia', models.CharField(blank=True, max_length=45, null=True)),
                ('num_interior', models.CharField(blank=True, max_length=10, null=True)),
                ('num_exterior', models.CharField(blank=True, max_length=10, null=True)),
                ('cp', models.CharField(blank=True, max_length=5, null=True)),
                ('municipio', models.CharField(blank=True, max_length=45, null=True)),
                ('localidad', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=45, null=True, unique=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Semin - Imagenologia',
            },
        ),
    ]
