# Generated by Django 2.1.7 on 2021-01-13 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel_radiologos', '0003_imagenologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizacionestudiodicom',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudios_actualizaciones', to='panel_radiologos.Imagenologia'),
        ),
    ]
