# Generated by Django 2.1.7 on 2021-01-15 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_radiologos', '0004_auto_20210112_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenologia',
            name='caducidad',
        ),
        migrations.RemoveField(
            model_name='imagenologia',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='imagenologia',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='imagenologia',
            name='colonia',
        ),
        migrations.RemoveField(
            model_name='imagenologia',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='imagenologia',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='imagenologia',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='imagenologia',
            name='estatusConexion',
        ),
        migrations.RemoveField(
            model_name='imagenologia',
            name='estrellas',
        ),
        migrations.RemoveField(
            model_name='imagenologia',
            name='estrellasArray',
        ),
        migrations.RemoveField(
            model_name='imagenologia',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='imagenologia',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='imagenologia',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='imagenologia',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='imagenologia',
            name='medicoSemin',
        ),
        migrations.RemoveField(
            model_name='imagenologia',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='imagenologia',
            name='num_exterior',
        ),
        migrations.RemoveField(
            model_name='imagenologia',
            name='num_interior',
        ),
        migrations.RemoveField(
            model_name='imagenologia',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='imagenologia',
            name='room',
        ),
        migrations.RemoveField(
            model_name='imagenologia',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='imagenologia',
            name='subespecialidad',
        ),
        migrations.RemoveField(
            model_name='imagenologia',
            name='ultimaConexion',
        ),
        migrations.RemoveField(
            model_name='imagenologia',
            name='verificado',
        ),
    ]
