# Generated by Django 2.1.7 on 2021-01-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_radiologos', '0005_auto_20210115_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenologia',
            name='water_mark',
            field=models.ImageField(blank=True, null=True, upload_to='images/water_marks'),
        ),
    ]
