# Generated by Django 2.1.7 on 2021-01-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_radiologos', '0006_imagenologia_water_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenologia',
            name='water_mark',
            field=models.ImageField(blank=True, null=True, upload_to='media/water_marks'),
        ),
    ]
