# Generated by Django 2.1.7 on 2021-02-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_radiologos', '0008_estudiodicom_liberado'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizacionestudiodicom',
            name='accion',
            field=models.CharField(choices=[('CREACION', 'CREACION'), ('CARGA_DE_INTERPRETACION', 'CARGA DE INTERPRETACION'), ('BORRADO_DE_INTERPRETACION', 'BORRADO DE INTERPRETACION'), ('OTRO', 'OTRO')], default='OTRO', max_length=64),
        ),
    ]
