import enum

class AccionEnum(enum.Enum):
    CREACION = 'CREACION'
    CARGA_DE_INTERPRETACION = 'CARGA DE INTERPRETACION'
    BORRADO_DE_INTERPRETACION = 'BORRADO DE INTERPRETACION'
    OTRO = 'OTRO'