# Generated by Django 2.2.5 on 2019-09-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horariosucursal',
            options={'verbose_name_plural': 'Semin - Sucursales - Horario de Sucursal'},
        ),
    ]
