# Generated by Django 2.2.5 on 2019-09-25 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('semin', '0002_auto_20190925_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='creator',
        ),
        migrations.AddField(
            model_name='paciente',
            name='editors',
            field=models.ManyToManyField(related_name='doctors', to=settings.AUTH_USER_MODEL),
        ),
    ]
