# Generated by Django 2.2.5 on 2019-09-25 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0004_auto_20190925_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='pacientes', to=settings.AUTH_USER_MODEL),
        ),
    ]
