# Generated by Django 2.2.5 on 2019-10-02 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0006_auto_20191002_1533'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DisponibilidadServicios',
            new_name='DisponibilidadServicio',
        ),
    ]
