# Generated by Django 2.2.5 on 2019-10-03 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0007_auto_20191002_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudio',
            name='Expediente',
        ),
        migrations.AddField(
            model_name='estudio',
            name='Paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Paciente'),
        ),
    ]
