# Generated by Django 2.1.7 on 2019-10-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0008_auto_20191003_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasucursal',
            name='tipo_estudio',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Doctor', 'Doctor'), ('Paciente', 'Paciente'), ('Operador', 'Operador')], max_length=9, null=True),
        ),
    ]
