# Generated by Django 2.1.7 on 2019-10-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0009_auto_20191009_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiempoServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tomaMuestrasPropio', models.IntegerField(default=0)),
                ('tomaMuestrasMaquila', models.IntegerField(default=0)),
                ('ultrasonografia', models.IntegerField(default=0)),
                ('rayosXSimple', models.IntegerField(default=0)),
                ('rayosXContrastados', models.IntegerField(default=0)),
                ('mastografia', models.IntegerField(default=0)),
                ('tomografiaSimple', models.IntegerField(default=0)),
                ('tomografiaContrastada', models.IntegerField(default=0)),
                ('resonanciaMagneticaSimple', models.IntegerField(default=0)),
                ('resonanciaMagneticaContrastada', models.IntegerField(default=0)),
                ('densitometria', models.IntegerField(default=0)),
                ('electrocardiograma', models.IntegerField(default=0)),
                ('papanicolau', models.IntegerField(default=0)),
                ('colposcopia', models.IntegerField(default=0)),
                ('audiologia', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Semin - Tiempo de Servicio ',
            },
        ),
    ]
