# Generated by Django 2.1.7 on 2019-10-11 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0010_tiemposervicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiemposervicio',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiemposervicio',
            name='ultimaActualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
