# Generated by Django 2.1.7 on 2019-10-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0011_auto_20191011_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiemposervicio',
            old_name='audiologia',
            new_name='Audio',
        ),
        migrations.RenameField(
            model_name='tiemposervicio',
            old_name='colposcopia',
            new_name='Colpo',
        ),
        migrations.RenameField(
            model_name='tiemposervicio',
            old_name='densitometria',
            new_name='Densi',
        ),
        migrations.RenameField(
            model_name='tiemposervicio',
            old_name='electrocardiograma',
            new_name='EKG',
        ),
        migrations.RenameField(
            model_name='tiemposervicio',
            old_name='mastografia',
            new_name='Maquila_lab',
        ),
        migrations.RenameField(
            model_name='tiemposervicio',
            old_name='papanicolau',
            new_name='Masto',
        ),
        migrations.RenameField(
            model_name='tiemposervicio',
            old_name='rayosXContrastados',
            new_name='Papa',
        ),
        migrations.RenameField(
            model_name='tiemposervicio',
            old_name='rayosXSimple',
            new_name='Propios_lab',
        ),
        migrations.RenameField(
            model_name='tiemposervicio',
            old_name='resonanciaMagneticaContrastada',
            new_name='RMC',
        ),
        migrations.RenameField(
            model_name='tiemposervicio',
            old_name='resonanciaMagneticaSimple',
            new_name='RMS',
        ),
        migrations.RenameField(
            model_name='tiemposervicio',
            old_name='tomaMuestrasMaquila',
            new_name='RXC',
        ),
        migrations.RenameField(
            model_name='tiemposervicio',
            old_name='tomaMuestrasPropio',
            new_name='RXS',
        ),
        migrations.RenameField(
            model_name='tiemposervicio',
            old_name='tomografiaContrastada',
            new_name='TACC',
        ),
        migrations.RenameField(
            model_name='tiemposervicio',
            old_name='tomografiaSimple',
            new_name='TACS',
        ),
        migrations.RenameField(
            model_name='tiemposervicio',
            old_name='ultrasonografia',
            new_name='US',
        ),
    ]
