# Generated by Django 2.1.7 on 2019-10-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0012_auto_20191011_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='electrocardiograma',
            new_name='Cons_1',
        ),
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='mastografia',
            new_name='Cons_2',
        ),
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='patologia',
            new_name='EKG_1',
        ),
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='rayosX',
            new_name='EKG_2',
        ),
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='rayosXContrastados',
            new_name='Masto_1',
        ),
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='resonanciaMagnetica',
            new_name='Masto_2',
        ),
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='tomaMuestras',
            new_name='Pato_1',
        ),
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='tomografia',
            new_name='Pato_2',
        ),
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='ultrasonografia',
            new_name='RM_1',
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='RM_2',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='RXC_1',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='RXC_2',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='RX_1',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='RX_2',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='TAC_1',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='TAC_2',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='US_1',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='US_2',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
