# Generated by Django 2.1.7 on 2019-10-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0013_auto_20191011_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogo',
            old_name='CitaSucrusal',
            new_name='CitaSucursal',
        ),
        migrations.RemoveField(
            model_name='catalogo',
            name='DIFPue',
        ),
        migrations.RemoveField(
            model_name='catalogo',
            name='ISSSTEPAtlixco',
        ),
        migrations.AddField(
            model_name='catalogo',
            name='categoria',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='sexo',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='beneficio',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='indicacionesPreExamen',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='prueba',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='sinAcro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='tipoMuestra',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
