# Generated by Django 2.1.7 on 2019-10-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0014_auto_20191011_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='tipoEstudio',
            field=models.CharField(blank=True, choices=[('Propios_lab', 'Propios_lab'), ('Maquila_lab', 'Maquila_lab'), ('US', 'US'), ('RXS', 'RXS'), ('RXC', 'RXC'), ('Masto', 'Masto'), ('TACS', 'TACS'), ('TACC', 'TACC'), ('RMS', 'RMS'), ('RMC', 'RMC'), ('Densi', 'Densi'), ('EKG', 'EKG'), ('Papa', 'Papa'), ('Colpo', 'Colpo'), ('Audio', 'Audio')], max_length=90, null=True),
        ),
    ]
