# Generated by Django 2.1.7 on 2019-10-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0019_auto_20191011_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='Audio_1',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='Audio_2',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='Clinica_1',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='Clinica_2',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='Clinica_3',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='Clinica_4',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='Clinica_5',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='Clinica_6',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='Clinica_7',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='Colpo_1',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='Colpo_2',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='Densi_1',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='Densi_2',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
