# Generated by Django 2.1.7 on 2019-10-22 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0020_auto_20191022_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='Clinica_1',
            new_name='Cli_1',
        ),
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='Clinica_2',
            new_name='Cli_2',
        ),
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='Clinica_3',
            new_name='Cli_3',
        ),
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='Clinica_4',
            new_name='Cli_4',
        ),
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='Clinica_5',
            new_name='Cli_5',
        ),
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='Clinica_6',
            new_name='Cli_6',
        ),
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='Clinica_7',
            new_name='Cli_7',
        ),
    ]
