# Generated by Django 2.1.7 on 2019-10-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0022_sucursal_estacionamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='dias_festivos',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='hora_apertura',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='hora_apertura_sab',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='hora_cierre',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='hora_cierre_sab',
            field=models.TimeField(null=True),
        ),
    ]
