# Generated by Django 2.1.7 on 2019-10-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0023_auto_20191024_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasFestivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_festividad', models.CharField(max_length=90, null=True)),
                ('fecha_festividad', models.DateField(null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Semin - Dias Festivos',
            },
        ),
    ]
