# Generated by Django 2.1.7 on 2019-10-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0024_diasfestivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='diasfestivos',
            name='dia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diasfestivos',
            name='mes',
            field=models.IntegerField(default=0),
        ),
    ]
