# Generated by Django 2.1.7 on 2019-10-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0027_auto_20191024_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='TACC_1',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='TACC_2',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
