# Generated by Django 2.1.7 on 2019-10-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0028_auto_20191024_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidadservicio',
            name='Pato_1',
        ),
        migrations.RemoveField(
            model_name='disponibilidadservicio',
            name='Pato_2',
        ),
        migrations.RemoveField(
            model_name='disponibilidadservicio',
            name='RX_1',
        ),
        migrations.RemoveField(
            model_name='disponibilidadservicio',
            name='RX_2',
        ),
        migrations.RemoveField(
            model_name='disponibilidadservicio',
            name='TACC_1',
        ),
        migrations.RemoveField(
            model_name='disponibilidadservicio',
            name='TACC_2',
        ),
        migrations.RemoveField(
            model_name='disponibilidadservicio',
            name='TACS_1',
        ),
        migrations.RemoveField(
            model_name='disponibilidadservicio',
            name='TACS_2',
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='RXS_1',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='RXS_2',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='TAC_1',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='TAC_2',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='tiemposervicio',
            name='Clinica',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='categoria',
            field=models.CharField(choices=[('Prop_lab', 'Prop_lab'), ('Maq_lab', 'Maq_lab'), ('US', 'US'), ('RXS', 'RXS'), ('RXC', 'RXC'), ('Masto', 'Masto'), ('Papa', 'Papa'), ('EKG', 'EKG'), ('TACS', 'TACS'), ('TACC', 'TACC'), ('RMS', 'RMS'), ('RMC', 'RMC'), ('Colpo', 'Colpo'), ('Densi', 'Densi'), ('Audio', 'Audio'), ('Clinica', 'Clinica')], max_length=45, null=True),
        ),
    ]
