# Generated by Django 2.1.7 on 2019-10-24 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0030_disponibilidadservicio_cons_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidadservicio',
            name='Cons_x',
        ),
    ]
