# Generated by Django 2.1.7 on 2019-10-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0031_remove_disponibilidadservicio_cons_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidadservicio',
            name='Audio_1',
        ),
        migrations.RemoveField(
            model_name='disponibilidadservicio',
            name='Audio_2',
        ),
        migrations.RemoveField(
            model_name='tiemposervicio',
            name='Audio',
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='categoria',
            field=models.CharField(choices=[('Prop_lab', 'Prop_lab'), ('Maq_lab', 'Maq_lab'), ('US', 'US'), ('RXS', 'RXS'), ('RXC', 'RXC'), ('Masto', 'Masto'), ('Papa', 'Papa'), ('EKG', 'EKG'), ('TACS', 'TACS'), ('TACC', 'TACC'), ('RMS', 'RMS'), ('RMC', 'RMC'), ('Colpo', 'Colpo'), ('Densi', 'Densi'), ('Audio', 'Audio'), ('Espiro', 'Espiro'), ('Clinica', 'Clinica')], max_length=45, null=True),
        ),
    ]
