# Generated by Django 2.1.7 on 2019-10-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0032_auto_20191024_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiemposervicio',
            name='Audio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tiemposervicio',
            name='Espiro',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tiemposervicio',
            name='Pato',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='categoria',
            field=models.CharField(choices=[('Prop_lab', 'Prop_lab'), ('Maq_lab', 'Maq_lab'), ('US', 'US'), ('RXS', 'RXS'), ('RXC', 'RXC'), ('Masto', 'Masto'), ('Papa', 'Papa'), ('EKG', 'EKG'), ('TACS', 'TACS'), ('TACC', 'TACC'), ('RMS', 'RMS'), ('RMC', 'RMC'), ('Colpo', 'Colpo'), ('Densi', 'Densi'), ('Audio', 'Audio'), ('Espiro', 'Espiro'), ('Pato', 'Pato'), ('Clinica', 'Clinica')], max_length=45, null=True),
        ),
    ]
