# Generated by Django 2.1.7 on 2019-10-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0033_auto_20191024_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='categoria',
            field=models.CharField(choices=[('Analisis Clínicos', 'Analisis Clínicos'), ('Ultrasonografía', 'Ultrasonografía'), ('Rayos X', 'Rayos X'), ('Rayos X Contrastados', 'Rayos X Contrastados'), ('Mastografía', 'Mastografía'), ('Papanicolau', 'Papanicolau'), ('Electrocardiograma', 'Electrocardiograma'), ('Tomografía', 'Tomografía'), ('Tomografía Contrastada', 'Tomografía Contrastada'), ('Resonancia Magnética', 'Resonancia Magnética'), ('Resonancia Magnética Contrastada', 'Resonancia Magnética Contrastada'), ('Colposcopía', 'Colposcopía'), ('Densitometría', 'Densitometría'), ('Audiología', 'Audiología'), ('Espirometría', 'Espirometría'), ('Patología', 'Patología'), ('Clínica', 'Clínica')], max_length=45, null=True),
        ),
    ]
