# Generated by Django 2.1.7 on 2019-10-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0034_auto_20191024_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='sala',
            field=models.CharField(choices=[('Cons', 'Cons'), ('US', 'US'), ('RXS', 'RXS'), ('RXC', 'RXC'), ('Masto', 'Masto'), ('EKG', 'EKG'), ('TAC', 'TAC'), ('RM', 'RM'), ('Colpo', 'Colpo'), ('Densi', 'Densi'), ('Cli', 'Cli')], max_length=45, null=True),
        ),
    ]
