# Generated by Django 2.1.7 on 2019-10-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0036_auto_20191025_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariosucursal',
            name='Sucursal',
        ),
        migrations.DeleteModel(
            name='HorarioSucursal',
        ),
    ]
