# Generated by Django 2.1.7 on 2019-10-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0039_auto_20191025_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasucursal',
            name='id_pago',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
