# Generated by Django 2.1.7 on 2019-10-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0041_auto_20191025_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citasucursal',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='citasucursal',
            name='prueba',
        ),
    ]
