# Generated by Django 2.1.7 on 2019-10-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0043_auto_20191025_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citasucursal',
            name='estatus',
            field=models.CharField(choices=[('ACTIVA', 'ACTIVA'), ('CERRADA', 'CERRADA'), ('CANCELADA', 'CANCELADA')], max_length=13, null=True),
        ),
    ]
