# Generated by Django 2.1.7 on 2019-10-30 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0046_remove_profile_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiemposervicio',
            name='Propios_lab',
        ),
    ]
