# Generated by Django 2.1.7 on 2019-10-30 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0047_remove_tiemposervicio_propios_lab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiemposervicio',
            old_name='Maquila_lab',
            new_name='Analisis',
        ),
    ]
