# Generated by Django 2.1.7 on 2019-10-31 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0048_auto_20191030_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citasucursal',
            name='Sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citaSucursal', to='semin.Sucursal'),
        ),
    ]
