# Generated by Django 2.1.7 on 2019-11-01 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0050_auto_20191031_1037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiasFestivos',
        ),
    ]
