# Generated by Django 2.1.7 on 2019-11-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0053_auto_20191104_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='dias_festivos',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='hora_apertura_dom',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='hora_cierre_dom',
            field=models.TimeField(null=True),
        ),
    ]
