# Generated by Django 2.1.7 on 2019-11-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0054_auto_20191107_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='domingos',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
