# Generated by Django 2.1.7 on 2019-11-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0055_catalogo_domingos'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasucursal',
            name='tipo_cita',
            field=models.CharField(choices=[('ABIERTA', 'ABIERTA'), ('AGENDADA', 'AGENDADA'), ('EXTERNA', 'EXTERNA')], max_length=8, null=True),
        ),
    ]
