# Generated by Django 2.1.7 on 2019-11-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0056_citasucursal_tipo_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasucursal',
            name='precioVenta',
            field=models.FloatField(null=True),
        ),
    ]
