# Generated by Django 2.1.7 on 2019-11-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0060_auto_20191113_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='RXC',
            field=models.IntegerField(default=0),
        ),
    ]
