# Generated by Django 2.1.7 on 2019-11-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0061_disponibilidadservicio_rxc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='categoria',
            field=models.CharField(choices=[('Analisis Sanguíneos', 'Analisis Sanguíneos'), ('Analisis Clínicos', 'Analisis Clínicos'), ('Ultrasonografía', 'Ultrasonografía'), ('Rayos X', 'Rayos X'), ('Rayos X Contrastados', 'Rayos X Contrastados'), ('Mastografía', 'Mastografía'), ('Papanicolau', 'Papanicolau'), ('Electrocardiograma', 'Electrocardiograma'), ('Tomografía', 'Tomografía'), ('Tomografía Contrastada', 'Tomografía Contrastada'), ('Resonancia Magnética', 'Resonancia Magnética'), ('Resonancia Magnética Contrastada', 'Resonancia Magnética Contrastada'), ('Colposcopía', 'Colposcopía'), ('Densitometría', 'Densitometría'), ('Audiología', 'Audiología'), ('Espirometría', 'Espirometría'), ('Patología', 'Patología')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='sala',
            field=models.CharField(blank=True, choices=[('Sang', 'Sang'), ('Esp', 'Esp'), ('US', 'US'), ('RXS', 'RXS'), ('RXC', 'RXC'), ('Masto', 'Masto'), ('EKG', 'EKG'), ('TAC', 'TAC'), ('RM', 'RM'), ('Colpo', 'Colpo'), ('Densi', 'Densi'), ('Cli', 'Cli'), ('Externo', 'Externo')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='citasucursal',
            name='categoria',
            field=models.CharField(choices=[('Analisis Sanguíneos', 'Analisis Sanguíneos'), ('Analisis Clínicos', 'Analisis Clínicos'), ('Ultrasonografía', 'Ultrasonografía'), ('Rayos X', 'Rayos X'), ('Rayos X Contrastados', 'Rayos X Contrastados'), ('Mastografía', 'Mastografía'), ('Papanicolau', 'Papanicolau'), ('Electrocardiograma', 'Electrocardiograma'), ('Tomografía', 'Tomografía'), ('Tomografía Contrastada', 'Tomografía Contrastada'), ('Resonancia Magnética', 'Resonancia Magnética'), ('Resonancia Magnética Contrastada', 'Resonancia Magnética Contrastada'), ('Colposcopía', 'Colposcopía'), ('Densitometría', 'Densitometría'), ('Audiología', 'Audiología'), ('Espirometría', 'Espirometría'), ('Patología', 'Patología')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='citasucursal',
            name='sala',
            field=models.CharField(choices=[('Sang', 'Sang'), ('Esp', 'Esp'), ('US', 'US'), ('RXS', 'RXS'), ('RXC', 'RXC'), ('Masto', 'Masto'), ('EKG', 'EKG'), ('TAC', 'TAC'), ('RM', 'RM'), ('Colpo', 'Colpo'), ('Densi', 'Densi'), ('Cli', 'Cli'), ('Externo', 'Externo')], max_length=45, null=True),
        ),
    ]
