# Generated by Django 2.1.7 on 2019-11-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0066_remove_citasucursal_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasucursal',
            name='creador',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='citasucursal',
            name='editor',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
