# Generated by Django 2.1.7 on 2019-11-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0068_auto_20191119_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='numExpediente',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
