# Generated by Django 2.1.7 on 2019-12-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0069_auto_20191125_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='numExpediente',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
