# Generated by Django 2.1.7 on 2019-12-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0070_paciente_numexpediente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citasucursal',
            name='tipo_cita',
            field=models.CharField(choices=[('ABIERTA', 'ABIERTA'), ('AGENDADA', 'AGENDADA'), ('EXTERNA', 'EXTERNA'), ('RESTRINGIDA', 'RESTRINGIDA')], max_length=8, null=True),
        ),
    ]
