# Generated by Django 2.1.7 on 2019-12-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0072_auto_20191209_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citasucursal',
            name='tipo_cita',
            field=models.CharField(choices=[('ABIERTA', 'ABIERTA'), ('AGENDADA', 'AGENDADA'), ('EXTERNA', 'EXTERNA'), ('RESTRINGIDA', 'RESTRINGIDA')], max_length=11, null=True),
        ),
    ]
