# Generated by Django 2.1.7 on 2019-12-11 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0074_auto_20191211_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='Catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Catalogo'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='caducidad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
