# Generated by Django 2.1.7 on 2019-12-11 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0075_auto_20191211_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='Catalogo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Catalogo'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='caducidad',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images/promociones'),
        ),
    ]
