# Generated by Django 2.1.7 on 2019-12-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0076_auto_20191211_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocion',
            name='Catalogo',
        ),
        migrations.AddField(
            model_name='promocion',
            name='Catalogo',
            field=models.ManyToManyField(null=True, to='semin.Catalogo'),
        ),
    ]
