# Generated by Django 2.1.7 on 2019-12-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0077_auto_20191211_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='Catalogo',
            field=models.ManyToManyField(to='semin.Catalogo'),
        ),
    ]
