# Generated by Django 2.1.7 on 2019-12-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0078_auto_20191211_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocion',
            name='Catalogo',
        ),
    ]
