# Generated by Django 2.1.7 on 2019-12-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0080_promocion_catalogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='caducidad',
            field=models.DateTimeField(null=True),
        ),
    ]
