# Generated by Django 2.1.7 on 2019-12-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0081_auto_20191212_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='caducidad',
            field=models.DateField(null=True),
        ),
    ]
