# Generated by Django 2.1.7 on 2019-12-12 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0082_auto_20191212_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocion',
            name='caducidad',
        ),
    ]
