# Generated by Django 2.1.7 on 2019-12-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0083_remove_promocion_caducidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='caducidad',
            field=models.DateField(null=True),
        ),
    ]
