# Generated by Django 2.1.7 on 2019-12-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0084_promocion_caducidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='indicacionesPreExamen',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F'), ('I', 'I')], max_length=1, null=True),
        ),
    ]
