# Generated by Django 2.1.7 on 2019-12-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0086_remove_promocion_indicacionespreexamen'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='estudio_inicial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
