# Generated by Django 2.1.7 on 2019-12-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0087_promocion_estudio_inicial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocion',
            old_name='estudio_inicial',
            new_name='estudioInicial',
        ),
    ]
