# Generated by Django 2.1.7 on 2019-12-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0088_auto_20191216_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='estudioInicial',
            field=models.IntegerField(null=True),
        ),
    ]
