# Generated by Django 2.1.7 on 2019-12-20 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0091_auto_20191220_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='Paciente',
        ),
        migrations.AddField(
            model_name='archivo',
            name='Estudio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Estudio'),
        ),
    ]
