# Generated by Django 2.1.7 on 2019-12-20 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0092_auto_20191220_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudio',
            name='Expediente',
        ),
        migrations.AddField(
            model_name='estudio',
            name='Paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Paciente'),
        ),
    ]
