# Generated by Django 2.1.7 on 2019-12-20 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0093_auto_20191220_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='url_estudio',
        ),
    ]
