# Generated by Django 2.1.7 on 2019-12-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0094_remove_archivo_url_estudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='file',
            field=models.FileField(default='Void', upload_to=''),
        ),
    ]
