# Generated by Django 2.1.7 on 2019-12-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0095_archivo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='file',
            field=models.FileField(null=True, upload_to='estudios/'),
        ),
    ]
