# Generated by Django 2.1.7 on 2019-12-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0096_auto_20191220_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='Estudio',
        ),
        migrations.AddField(
            model_name='estudio',
            name='creador',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='editor',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='file',
            field=models.FileField(null=True, upload_to='estudios/'),
        ),
        migrations.DeleteModel(
            name='Archivo',
        ),
    ]
