# Generated by Django 2.1.7 on 2019-12-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0097_auto_20191223_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='fechaEstudio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='tipoEstudio',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
