# Generated by Django 2.1.7 on 2019-12-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0099_remove_estudio_fechaestudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='fileDicom',
            field=models.FileField(null=True, upload_to='estudios/'),
        ),
    ]
