# Generated by Django 2.1.7 on 2019-12-24 20:47

from django.db import migrations, models
import semin.models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0101_auto_20191224_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='file',
            field=models.FileField(null=True, upload_to='estudios/', validators=[semin.models.Estudio.validate_file]),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='fileDicom',
            field=models.FileField(blank=True, null=True, upload_to='estudios/', validators=[semin.models.Estudio.validate_file_dicom]),
        ),
    ]
