# Generated by Django 2.1.7 on 2019-12-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0102_auto_20191224_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='num_tarjeta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
