# Generated by Django 2.1.7 on 2019-12-31 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0103_paciente_num_tarjeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='num_tarjeta',
        ),
    ]
