# Generated by Django 2.1.7 on 2020-01-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0106_auto_20200117_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='Card',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='Cons',
            field=models.IntegerField(default=0),
        ),
    ]
