# Generated by Django 2.1.7 on 2020-01-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0109_auto_20200124_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiemposervicio',
            old_name='Esp',
            new_name='Cli',
        ),
    ]
