# Generated by Django 2.1.7 on 2020-01-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0110_auto_20200124_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiemposervicio',
            old_name='Cli',
            new_name='Esp',
        ),
    ]
