# Generated by Django 2.1.7 on 2020-01-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0113_catalogo_domingos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='prueba',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='sinAcro',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='tiempoEntrega',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='tipoMuestra',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
