# Generated by Django 2.1.7 on 2020-01-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0115_auto_20200130_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='USD',
            field=models.IntegerField(default=0),
        ),
    ]
