# Generated by Django 2.1.7 on 2020-01-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0117_auto_20200130_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citasucursal',
            name='notas',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='citasucursal',
            name='prueba',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
