# Generated by Django 2.1.7 on 2020-01-30 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0118_auto_20200130_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='Papa',
            new_name='Pato',
        ),
    ]
