# Generated by Django 2.1.7 on 2020-01-30 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0120_auto_20200130_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiemposervicio',
            old_name='EKG',
            new_name='Card',
        ),
    ]
