# Generated by Django 2.1.7 on 2020-01-30 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0121_auto_20200130_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidadservicio',
            name='Card',
        ),
    ]
