# Generated by Django 2.1.7 on 2020-01-30 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0122_remove_disponibilidadservicio_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='EKG',
            new_name='Card',
        ),
    ]
