# Generated by Django 2.1.7 on 2020-02-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0123_auto_20200130_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='hab1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='hab2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='hab3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='hab4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='hab5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='hab6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='hab7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='inc1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='inc2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='quir1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='quir2',
            field=models.IntegerField(default=0),
        ),
    ]
