# Generated by Django 2.1.7 on 2020-02-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0124_auto_20200204_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='hab1',
            new_name='Exp1',
        ),
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='hab2',
            new_name='Hab1',
        ),
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='hab3',
            new_name='Hab2',
        ),
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='hab4',
            new_name='Hab3',
        ),
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='hab5',
            new_name='Hab4',
        ),
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='hab6',
            new_name='Hab5',
        ),
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='hab7',
            new_name='Hab6',
        ),
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='inc1',
            new_name='Hab7',
        ),
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='inc2',
            new_name='Inc1',
        ),
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='quir1',
            new_name='Inc2',
        ),
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='quir2',
            new_name='Quir1',
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='Quir2',
            field=models.IntegerField(default=0),
        ),
    ]
