# Generated by Django 2.1.7 on 2020-02-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0128_auto_20200220_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasucursal',
            name='razon_rembolso',
            field=models.CharField(blank=True, choices=[('Uno', 'Uno'), ('Dos', 'Dos'), ('Tres', 'Tres')], max_length=30, null=True),
        ),
    ]
