# Generated by Django 2.1.7 on 2020-02-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0129_citasucursal_razon_rembolso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='hora_apertura_dom',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='hora_cierre_dom',
        ),
        migrations.AlterField(
            model_name='citasucursal',
            name='estatus_rembolso',
            field=models.CharField(blank=True, choices=[('SOLICITADO', 'SOLICITADO'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO')], max_length=10, null=True),
        ),
    ]
