# Generated by Django 2.1.7 on 2020-03-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0132_auto_20200302_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citasucursal',
            name='estatus_facturacion',
        ),
        migrations.AddField(
            model_name='facturacion',
            name='analisis_clinicos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='calle',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='cantidad_pagada',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='cfdi',
            field=models.CharField(blank=True, choices=[('P01-Por definir', 'P01-Por definir'), ('G03-Gastos en general', 'G03-Gastos en general'), ('D01-Honorarios medicos dentales y gastos hospitalarios', 'D01-Honorarios medicos dentales y gastos hospitalarios')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='colonia',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='cp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='descripcion_servicios',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='email',
            field=models.EmailField(max_length=45, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='estado',
            field=models.CharField(blank=True, choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('CDMX', 'CDMX'), ('Chihuahua', 'Chihuahua'), ('Chiapas', 'Chiapas'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('México', 'México'), ('Michoacán', 'Michoacán'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Ro', 'Quintana Ro'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='estudios_realizados',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('01-Efectivo', '01-Efectivo'), ('03-Transferencia electrónica de fondos', '03-Transferencia electrónica de fondos'), ('04-Tarjeta de crédito', '04-Tarjeta de crédito'), ('28-Tarjeta de debito', '28-Tarjeta de debito'), ('99-Por definir', '99-Por definir')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='localidad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('PDD-Pago en parcialidades o diferido', 'PDD-Pago en parcialidades o diferido'), ('PUE-Pago en una sola exhibición', 'PUE-Pago en una sola exhibición')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='municipio',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='nombre_estudio',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='num_expediente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='num_exterior',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='num_folio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='num_interior',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='nombre',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='rfc',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='tipo_rfc',
            field=models.CharField(choices=[('FISICA', 'FISICA'), ('MORAL', 'MORAL')], max_length=6, null=True),
        ),
    ]
