# Generated by Django 2.1.7 on 2020-03-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0141_auto_20200303_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='factura_estatus',
            field=models.CharField(choices=[('SOLICITADO', 'SOLICITADO'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO')], max_length=10, null=True),
        ),
    ]
