# Generated by Django 2.1.7 on 2020-03-04 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0142_auto_20200303_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citasucursal',
            name='Paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='semin.Paciente'),
        ),
    ]
