# Generated by Django 2.1.7 on 2020-03-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0144_facturacion_notas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturacion',
            old_name='notas',
            new_name='observaciones',
        ),
    ]
