# Generated by Django 2.1.7 on 2020-03-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0145_auto_20200304_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='cantidad_pagada',
            field=models.FloatField(null=True),
        ),
    ]
