# Generated by Django 2.1.7 on 2020-03-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0148_auto_20200309_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasucursal',
            name='app_movil',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
