# Generated by Django 2.1.7 on 2020-03-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0150_auto_20200310_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturacion',
            name='descripcion_servicios',
        ),
        migrations.AddField(
            model_name='facturacion',
            name='nombre_paciente',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
