# Generated by Django 2.1.7 on 2020-03-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0151_auto_20200311_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='RehaEle1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='RehaEle2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='RehaEle3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='RehaEle4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='RehaEle5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='RehaEle6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='RehaEle7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='RehaEle8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='RehaHid1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='RehaMec1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tiemposervicio',
            name='RehaEle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tiemposervicio',
            name='RehaHid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tiemposervicio',
            name='RehaMec',
            field=models.IntegerField(default=0),
        ),
    ]
