# Generated by Django 2.1.7 on 2020-03-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0152_auto_20200317_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='otrasIndicacionesn',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='ranking',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
