# Generated by Django 2.1.7 on 2020-03-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0153_auto_20200319_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogo',
            old_name='otrasIndicacionesn',
            new_name='otrasIndicaciones',
        ),
    ]
