# Generated by Django 2.1.7 on 2020-03-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0154_auto_20200319_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Medico', 'Medico'), ('Paciente', 'Paciente'), ('Operador', 'Operador'), ('Administrador', 'Administrador')], max_length=9, null=True),
        ),
    ]
