# Generated by Django 2.1.7 on 2020-03-20 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0156_admin_medico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name_plural': 'Semin - Administradores'},
        ),
    ]
