# Generated by Django 2.1.7 on 2020-03-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0158_primeraencuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primeraencuesta',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numExpediente',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
