# Generated by Django 2.1.7 on 2020-04-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0160_auto_20200331_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='primeraencuesta',
            name='titulo',
            field=models.CharField(default='Primera Encuesta', max_length=10),
        ),
    ]
