# Generated by Django 2.1.7 on 2020-04-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0161_primeraencuesta_titulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrimeraEncuesta',
        ),
    ]
