# Generated by Django 2.1.7 on 2020-04-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0163_primeraencuesta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='primeraencuesta',
            options={'verbose_name_plural': 'Encuesta - Primera'},
        ),
    ]
