# Generated by Django 2.1.7 on 2020-04-02 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0164_auto_20200402_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primeraencuesta',
            name='titulo',
        ),
    ]
