# Generated by Django 2.1.7 on 2020-04-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0165_remove_primeraencuesta_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primeraencuesta',
            name='preguntaDos',
            field=models.CharField(choices=[('Analisis _Sanguineos', 'Analisis Sanguineos'), ('Analisis_Clinicos', 'Analisis Clinicos'), ('Ultrasonografia', 'Ultrasonografia'), ('Ultrasonografia_Doppler', 'Ultrasonografia Doppler'), ('Rayos_X', 'Rayos X'), ('Rayos_X Contrastados', 'Rayos X Contrastados'), ('Mastografia', 'Mastografia'), ('Papanicolau', 'Papanicolau'), ('Tomografia', 'Tomografia'), ('Tomografia_Contrastada', 'Tomografia Contrastada'), ('Resonancia_Magnetica', 'Resonancia Magnetica'), ('Resonancia_Magnetica Contrastada', 'Resonancia Magnetica Contrastada'), ('Colposcopia', 'Colposcopia'), ('Densitometria', 'Densitometria'), ('Audiologia', 'Audiologia'), ('Espirometria', 'Espirometria'), ('Patologia', 'Patologia'), ('Consulta', 'Consulta'), ('Cardiologia', 'Cardiologia'), ('Rehabilitacion', 'Rehabilitacion')], max_length=50),
        ),
    ]
