# Generated by Django 2.1.7 on 2020-04-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0169_consulta_historiaclinica_informemedico'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nombrex',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
