# Generated by Django 2.1.7 on 2020-04-03 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0170_paciente_nombrex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='nombrex',
        ),
    ]
