# Generated by Django 2.1.7 on 2020-04-03 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0172_promocion_indicaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocion',
            name='imagen_miniatura',
        ),
    ]
