# Generated by Django 2.1.7 on 2020-04-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0174_auto_20200403_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primeraencuesta',
            name='preguntaDos',
            field=models.CharField(choices=[('0', 'Analisis Sanguineos'), ('1', 'Analisis Clinicos'), ('2', 'Ultrasonografia'), ('3', 'Ultrasonografia Doppler'), ('4', 'Rayos X'), ('5', 'Rayos X Contrastados'), ('6', 'Mastografia'), ('7', 'Papanicolau'), ('8', 'Tomografia'), ('9', 'Tomografia Contrastada'), ('10', 'Resonancia Magnetica'), ('11', 'Resonancia Magnetica Contrastada'), ('12', 'Colposcopia'), ('13', 'Densitometria'), ('14', 'Audiologia'), ('15', 'Espirometria'), ('16', 'Patologia'), ('17', 'Consulta'), ('18', 'Cardiologia'), ('19', 'Rehabilitacion')], max_length=50),
        ),
    ]
