# Generated by Django 2.1.7 on 2020-04-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0178_auto_20200406_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primeraencuesta',
            name='preguntaTres',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=10),
        ),
    ]
