# Generated by Django 2.1.7 on 2020-04-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0179_auto_20200406_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='preguntaUno',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='frecuenciaCardiaca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='frecuenciaRespiratoria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='indiceMasaCorporal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='presionArterialDiastole',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='presionArterialSistole',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='talla',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='temperatura',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
