# Generated by Django 2.1.7 on 2020-04-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0180_auto_20200407_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='estadoCivil',
            field=models.CharField(blank=True, choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Concubinato', 'Concubinato'), ('Viudo', 'Viudo'), ('Divorciado', 'Divorciado'), ('Separado', 'Separado')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='hijos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='maxGradoEstudios',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='numHijos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
