# Generated by Django 2.1.7 on 2020-04-07 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0181_auto_20200407_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='Paciente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Paciente'),
        ),
    ]
