# Generated by Django 2.1.7 on 2020-04-07 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0182_historiaclinica_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='Paciente',
        ),
        migrations.AlterModelOptions(
            name='consulta',
            options={'verbose_name_plural': 'Pacientes - Consulta'},
        ),
        migrations.AlterModelOptions(
            name='historiaclinica',
            options={'verbose_name_plural': 'Pacientes - Historia Clinica'},
        ),
        migrations.AlterModelOptions(
            name='informemedico',
            options={'verbose_name_plural': 'Pacientes - Informe Medico'},
        ),
        migrations.DeleteModel(
            name='Expediente',
        ),
    ]
