# Generated by Django 2.1.7 on 2020-04-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0184_auto_20200407_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='sistemaDigestivo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='sistemaMusculoEsqueletico',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='sistemaNeurologico',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='sistemaReproductor',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='sistemaRespiratorio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='sistemaTegumentario',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='sistemaUrinario',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='sistemasSentidos',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
