# Generated by Django 2.1.7 on 2020-04-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0185_auto_20200408_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='Paciente',
        ),
    ]
