# Generated by Django 2.1.7 on 2020-04-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0187_historiaclinica_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='Paciente',
        ),
        migrations.DeleteModel(
            name='HistoriaClinica',
        ),
    ]
