# Generated by Django 2.1.7 on 2020-04-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0189_historiaclinica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiaclinica',
            old_name='presionArterialDiastole',
            new_name='tensionArterialDiastole',
        ),
        migrations.RenameField(
            model_name='historiaclinica',
            old_name='presionArterialSistole',
            new_name='tensionnArterialSistole',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='preguntaUno',
        ),
        migrations.AddField(
            model_name='consulta',
            name='analisis',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='clinicos',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='frecuenciaCardiaca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='frecuenciaRespiratoria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='impresionDiagnostica',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='indiceMasaCorporal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='manejoRecomendaciones',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='objetivo',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='plan',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='sexo',
            field=models.CharField(blank=True, choices=[('masculino', 'masculino'), ('femenino', 'femenino')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='subjetivo',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='talla',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='temperatura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='tensionArterialDiastole',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='tensionnArterialSistole',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='sexo',
            field=models.CharField(blank=True, choices=[('masculino', 'masculino'), ('femenino', 'femenino')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='sistemaDigestivo',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='sistemaMusculoEsqueletico',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='sistemaNeurologico',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='sistemaReproductor',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='sistemaRespiratorio',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='sistemaTegumentario',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='sistemaUrinario',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='sistemasSentidos',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
