# Generated by Django 2.1.7 on 2020-04-08 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0191_auto_20200408_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'verbose_name_plural': 'Pacientes - Expediente - Historia Clinica'},
        ),
        migrations.AlterModelOptions(
            name='historiaclinica',
            options={'verbose_name_plural': 'Pacientes - Expediente - Historia Clinica'},
        ),
    ]
