# Generated by Django 2.1.7 on 2020-04-08 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0192_auto_20200408_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'verbose_name_plural': 'Pacientes - Expediente - Consulta'},
        ),
    ]
