# Generated by Django 2.1.7 on 2020-04-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0194_auto_20200408_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='Paciente',
            new_name='HistoriaClinica',
        ),
        migrations.RenameField(
            model_name='historiaclinica',
            old_name='tensionnArterialSistole',
            new_name='tensionArterialSistole',
        ),
    ]
