# Generated by Django 2.1.7 on 2020-04-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0195_auto_20200413_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='HistoriaClinica',
        ),
    ]
