# Generated by Django 2.1.7 on 2020-04-13 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0196_remove_consulta_historiaclinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='Paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Paciente'),
        ),
    ]
