# Generated by Django 2.1.7 on 2020-04-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0199_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='domicilio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
