# Generated by Django 2.1.7 on 2020-04-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0202_catalogo_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='clave',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
