# Generated by Django 2.1.7 on 2020-04-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0203_auto_20200414_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablapermisos',
            name='caducidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablapermisos',
            name='correoDoctor',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='tablapermisos',
            name='externo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablapermisos',
            name='token',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
