# Generated by Django 2.1.7 on 2020-04-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0204_auto_20200414_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablapermisos',
            name='Paciente',
        ),
        migrations.DeleteModel(
            name='TablaPermisos',
        ),
    ]
