# Generated by Django 2.1.7 on 2020-04-14 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0205_auto_20200414_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaPermisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=60, null=True)),
                ('caducidad', models.DateField(blank=True, null=True)),
                ('correoDoctor', models.CharField(blank=True, max_length=60, null=True)),
                ('externo', models.BooleanField(blank=True, default=True, null=True)),
                ('creador', models.CharField(max_length=90, null=True)),
                ('editor', models.CharField(max_length=90, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
                ('Paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Paciente')),
            ],
            options={
                'verbose_name_plural': 'Pacientes - Expediente - Tabla de Permisos',
            },
        ),
    ]
