# Generated by Django 2.1.7 on 2020-04-14 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0206_tablapermisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablapermisos',
            name='Paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Paciente'),
        ),
        migrations.AlterField(
            model_name='tablapermisos',
            name='creador',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='tablapermisos',
            name='editor',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
