# Generated by Django 2.1.7 on 2020-04-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0208_auto_20200414_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='ConsFis1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='ConsFis2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='ConsFis3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='ConsPed',
            field=models.IntegerField(default=0),
        ),
    ]
