# Generated by Django 2.1.7 on 2020-04-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0211_auto_20200423_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citamedico',
            name='titulo',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
