# Generated by Django 2.1.7 on 2020-04-29 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0213_auto_20200428_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='Paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Paciente'),
        ),
    ]
