# Generated by Django 2.1.7 on 2020-05-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0214_auto_20200429_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='citamedico',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citamedico',
            name='unidadEnvio',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='medicoSemin',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
