# Generated by Django 2.1.7 on 2020-05-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0215_auto_20200504_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citamedico',
            name='unidadEnvio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
