# Generated by Django 2.1.7 on 2020-05-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0216_auto_20200504_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='puesto',
        ),
        migrations.AddField(
            model_name='medico',
            name='cedula',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('Medicina Interna', 'Medicina Interna'), ('Cirugía', 'Cirugía'), ('Endocrinología', 'Endocrinología'), ('Ginecología', 'Ginecología'), ('Nefrología', 'Nefrología'), ('Neurocirugía', 'Neurocirugía'), ('Neurología', 'Neurología'), ('Pediatría', 'Pediatría'), ('Traumatología y Ortopedia', 'Traumatología y Ortopedia'), ('Urología', 'Urología')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='estado',
            field=models.CharField(blank=True, choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('CDMX', 'CDMX'), ('Chihuahua', 'Chihuahua'), ('Chiapas', 'Chiapas'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('México', 'México'), ('Michoacán', 'Michoacán'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Ro', 'Quintana Ro'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/doctores'),
        ),
        migrations.AddField(
            model_name='medico',
            name='verificado',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
