# Generated by Django 2.1.7 on 2020-05-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0217_auto_20200505_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='ranking',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
