# Generated by Django 2.1.7 on 2020-05-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0219_medico_caducidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='estrellas',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
