# Generated by Django 2.1.7 on 2020-05-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0220_medico_estrellas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='descripcion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
