# Generated by Django 2.1.7 on 2020-05-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0221_auto_20200507_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='calle',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='colonia',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='cp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='localidad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='municipio',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='num_exterior',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='num_interior',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
