# Generated by Django 2.1.7 on 2020-05-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0222_auto_20200507_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoOpenPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(max_length=90, null=True)),
                ('product_name', models.CharField(max_length=90, null=True)),
                ('paypal_sdk_version', models.CharField(max_length=90, null=True)),
                ('platform', models.CharField(max_length=90, null=True)),
                ('response_type', models.CharField(max_length=90, null=True)),
                ('response', models.CharField(max_length=90, null=True)),
                ('id_pay', models.CharField(max_length=90, null=True)),
                ('state', models.CharField(max_length=90, null=True)),
                ('create_time', models.CharField(max_length=90, null=True)),
                ('intent', models.CharField(max_length=90, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Semin - Pago Open Pay',
            },
        ),
    ]
