# Generated by Django 2.1.7 on 2020-05-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0224_auto_20200515_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoopenpay',
            name='citaSucursal',
        ),
        migrations.AddField(
            model_name='pagoopenpay',
            name='id_cita',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
