# Generated by Django 2.1.7 on 2020-05-15 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0225_auto_20200515_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoopenpay',
            name='Paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Paciente'),
        ),
    ]
