# Generated by Django 2.1.7 on 2020-05-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0229_auto_20200518_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='informador',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='tipoInterogatorio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
