# Generated by Django 2.1.7 on 2020-05-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0230_auto_20200518_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='tipoInterogatorio',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='tipoInterrogatorio',
            field=models.CharField(blank=True, choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Concubinato', 'Concubinato'), ('Viudo', 'Viudo'), ('Divorciado', 'Divorciado'), ('Separado', 'Separado')], max_length=10, null=True),
        ),
    ]
