# Generated by Django 2.1.7 on 2020-05-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0233_disponibilidadservicio_servdom'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/pacientes'),
        ),
    ]
