# Generated by Django 2.1.7 on 2020-05-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0234_paciente_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='precioApoyo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='precioNormal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
