# Generated by Django 2.1.7 on 2020-05-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0235_auto_20200522_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
