# Generated by Django 2.1.7 on 2020-05-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0236_auto_20200525_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('Medicina Interna', 'Medicina Interna'), ('Cirugia', 'Cirugía'), ('Endocrinologia', 'Endocrinología'), ('Ginecologia', 'Ginecología'), ('Nefrologia', 'Nefrología'), ('Neurocirugia', 'Neurocirugía'), ('Neurologia', 'Neurología'), ('Pediatria', 'Pediatría'), ('Traumatologia y Ortopedia', 'Traumatología y Ortopedia'), ('Urologia', 'Urología')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('Medicina Interna', 'Medicina Interna'), ('Cirugia', 'Cirugía'), ('Endocrinologia', 'Endocrinología'), ('Ginecologia', 'Ginecología'), ('Nefrologia', 'Nefrología'), ('Neurocirugia', 'Neurocirugía'), ('Neurologia', 'Neurología'), ('Pediatria', 'Pediatría'), ('Traumatologia y Ortopedia', 'Traumatología y Ortopedia'), ('Urologia', 'Urología')], max_length=30, null=True),
        ),
    ]
