# Generated by Django 2.1.7 on 2020-05-27 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0241_consulta_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='notaCinco',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='notaOcho',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='notaSeis',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='notaSiete',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='tituloCinco',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='tituloOcho',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='tituloSeis',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='tituloSiete',
        ),
    ]
