# Generated by Django 2.1.7 on 2020-06-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0243_auto_20200602_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablapermisos',
            name='estatus',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], max_length=9, null=True),
        ),
    ]
