# Generated by Django 2.1.7 on 2020-06-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0246_auto_20200608_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablapermisos',
            name='email',
            field=models.EmailField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='tablapermisos',
            name='token',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
