# Generated by Django 2.1.7 on 2020-06-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0247_auto_20200610_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='estatusConexion',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], max_length=10, null=True),
        ),
    ]
