# Generated by Django 2.1.7 on 2020-06-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0248_medico_estatusconexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='ultimaConexion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
