# Generated by Django 2.1.7 on 2020-06-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0249_medico_ultimaconexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='ServDomRx',
            field=models.IntegerField(default=0),
        ),
    ]
