# Generated by Django 2.1.7 on 2020-06-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0251_auto_20200622_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Medico', 'Medico'), ('Paciente', 'Paciente'), ('Operador', 'Operador'), ('Administrador', 'Administrador')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='tablapermisos',
            name='tipo',
            field=models.CharField(choices=[('INTERNO', 'INTERNO'), ('EXTERNO', 'EXTERNO')], max_length=9, null=True),
        ),
    ]
