# Generated by Django 2.1.7 on 2020-06-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0252_auto_20200622_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='verificado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('APROVADO', 'APROVADO'), ('RECHAZADO', 'RECHAZADO')], default='PENDIENTE', max_length=11, null=True),
        ),
    ]
