# Generated by Django 2.1.7 on 2020-06-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0255_auto_20200623_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='estrellas',
            field=models.IntegerField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='ranking',
            field=models.IntegerField(default=500, null=True),
        ),
    ]
