# Generated by Django 2.1.7 on 2020-06-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0256_auto_20200624_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='caducidad',
            field=models.DateField(null=True),
        ),
    ]
