# Generated by Django 2.1.7 on 2020-06-26 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0259_medico_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablapermisos',
            name='Medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='semin.Medico'),
        ),
        migrations.AlterField(
            model_name='tablapermisos',
            name='Paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='semin.Paciente'),
        ),
    ]
