# Generated by Django 2.1.7 on 2020-06-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0261_auto_20200626_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
