# Generated by Django 2.1.7 on 2020-06-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0262_auto_20200629_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='Covid',
            field=models.IntegerField(default=0),
        ),
    ]
