# Generated by Django 2.1.7 on 2020-07-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0263_disponibilidadservicio_covid'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacion',
            name='empresa',
            field=models.CharField(blank=True, default='semin', max_length=10, null=True),
        ),
    ]
