# Generated by Django 2.1.7 on 2020-07-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0264_facturacion_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacion',
            name='sucursal',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
