# Generated by Django 2.1.7 on 2020-07-03 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0265_facturacion_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablapermisos',
            name='Paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Paciente'),
        ),
    ]
