# Generated by Django 2.1.7 on 2020-07-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0268_auto_20200706_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='tipoInterrogatorio',
            field=models.CharField(blank=True, choices=[('DIRECTO', 'DIRECTO'), ('INDIRECTO', 'INDIRECTO'), ('MIXTO', 'MIXTO')], max_length=10, null=True),
        ),
    ]
