# Generated by Django 2.1.7 on 2020-07-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0269_auto_20200708_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='email',
            field=models.EmailField(blank=True, max_length=45, null=True),
        ),
    ]
