# Generated by Django 2.1.7 on 2020-07-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0270_auto_20200714_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='auditor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
