# Generated by Django 2.1.7 on 2020-07-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0271_empleado_auditor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disponibilidadservicio',
            old_name='ServDom',
            new_name='ServDom1',
        ),
    ]
