# Generated by Django 2.1.7 on 2020-07-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0272_auto_20200723_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='ServDom2',
            field=models.IntegerField(default=0),
        ),
    ]
