# Generated by Django 2.1.7 on 2020-07-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0274_historicopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicopago',
            name='data',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
