# Generated by Django 2.1.7 on 2020-07-31 17:22

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0275_historicopago_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocionTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=90, null=True)),
                ('descripcion', models.CharField(max_length=400, null=True)),
                ('indicaciones', models.CharField(max_length=400, null=True)),
                ('precioVenta', models.FloatField(null=True)),
                ('numVentas', models.IntegerField(null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F'), ('I', 'I')], max_length=1, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='images/promociones')),
                ('caducidad', models.DateField(null=True)),
                ('estudioInicial', models.IntegerField(null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
                ('Catalogo', sortedm2m.fields.SortedManyToManyField(help_text=None, to='semin.Catalogo')),
            ],
            options={
                'verbose_name_plural': 'Semin - Catálogo de Promociónes Ticket',
            },
        ),
    ]
