# Generated by Django 2.1.7 on 2020-08-05 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0278_cosnsultasclientes_origen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CosnsultasClientes',
            new_name='ConsultasClientes',
        ),
    ]
