# Generated by Django 2.1.7 on 2020-08-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0279_auto_20200805_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasucursal',
            name='costoSucursal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('Medicina General', 'Medicina General'), ('Medicina Interna', 'Medicina Interna'), ('Cirugia', 'Cirugía'), ('Endocrinologia', 'Endocrinología'), ('Ginecologia', 'Ginecología'), ('Nefrologia', 'Nefrología'), ('Neurocirugia', 'Neurocirugía'), ('Neurologia', 'Neurología'), ('Pediatria', 'Pediatría'), ('Traumatologia y Ortopedia', 'Traumatología y Ortopedia'), ('Urologia', 'Urología')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(choices=[('Medicina General', 'Medicina General'), ('Medicina Interna', 'Medicina Interna'), ('Cirugia', 'Cirugía'), ('Endocrinologia', 'Endocrinología'), ('Ginecologia', 'Ginecología'), ('Nefrologia', 'Nefrología'), ('Neurocirugia', 'Neurocirugía'), ('Neurologia', 'Neurología'), ('Pediatria', 'Pediatría'), ('Traumatologia y Ortopedia', 'Traumatología y Ortopedia'), ('Urologia', 'Urología')], max_length=30, null=True),
        ),
    ]
