# Generated by Django 2.1.7 on 2020-08-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0282_disponibilidadservicio_covid2'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='id_zoom',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='password_zoom',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
