# Generated by Django 2.1.7 on 2020-08-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0284_callcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcenter',
            name='experiencia2',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
