# Generated by Django 2.1.7 on 2020-08-31 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0285_callcenter_experiencia2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callcenter',
            options={'verbose_name_plural': 'Semin - Call Center'},
        ),
        migrations.RemoveField(
            model_name='callcenter',
            name='experiencia2',
        ),
    ]
