# Generated by Django 2.1.7 on 2020-08-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0286_auto_20200831_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callcenter',
            name='experiencia',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
