# Generated by Django 2.1.7 on 2020-09-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0287_auto_20200831_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='password_zoom',
            new_name='id_room_zoom',
        ),
        migrations.AlterField(
            model_name='medico',
            name='id_zoom',
            field=models.EmailField(blank=True, max_length=45, null=True),
        ),
    ]
