# Generated by Django 2.1.7 on 2020-09-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0288_auto_20200909_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='beneficio',
            field=models.CharField(max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='clave',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
