# Generated by Django 2.1.7 on 2020-09-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0289_auto_20200909_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='versionCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('ANDROID_DS', 'ANDROID_DS'), ('IOS_DS', 'IOS_DS'), ('ANDROID_V', 'ANDROID_V'), ('IOS_V', 'IOS_V')], max_length=10, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Semin - Versión Dispositivos Móviles',
            },
        ),
    ]
