# Generated by Django 2.1.7 on 2020-09-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0292_medico_token_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='citamedico',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('OPENPAY', 'OPENPAY'), ('PAYPAL', 'PAYPAL'), ('STRIPE', 'STRIPE')], max_length=10, null=True),
        ),
    ]
