# Generated by Django 2.1.7 on 2020-09-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0293_citamedico_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='antecedentesFamiliares',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='antecedentesPersonalesNoPatologicos',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='antecedentesPersonalesPatologicos',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='auxiliaresDiagnostico',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='procedimientoActual',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='citamedico',
            name='fecha_cita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citamedico',
            name='hora_final',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citamedico',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
