# Generated by Django 2.1.7 on 2020-09-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0294_auto_20200929_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='fecha_subida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
