# Generated by Django 2.1.7 on 2020-10-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0296_auto_20200930_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasucursal',
            name='otro_fecha_nacimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citasucursal',
            name='otro_nombre_paciente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='citasucursal',
            name='otro_parentesco_paciente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
