# Generated by Django 2.1.7 on 2020-10-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0297_auto_20201001_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='ConsReha',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='citasucursal',
            name='otro_parentesco_paciente',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
