# Generated by Django 2.1.7 on 2020-10-08 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0298_auto_20201005_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citasucursal',
            name='otro_fecha_nacimento',
        ),
        migrations.RemoveField(
            model_name='citasucursal',
            name='otro_nombre_paciente',
        ),
        migrations.RemoveField(
            model_name='citasucursal',
            name='otro_parentesco_paciente',
        ),
    ]
