# Generated by Django 2.1.7 on 2020-10-21 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0300_auto_20201009_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(blank=True, max_length=40, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('num_recibo', models.IntegerField(blank=True, null=True)),
                ('nombre_paciente', models.CharField(max_length=100, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=45, null=True)),
                ('estudios_solicitados', models.CharField(blank=True, max_length=300, null=True)),
                ('como_entero', models.CharField(blank=True, choices=[('Anuncio en la calle', 'Anuncio en la calle'), ('Volantes/Folletos', 'Volantes/Folletos'), ('Internet', 'Internet'), ('Recomendacion', 'Recomendacion')], max_length=20, null=True)),
                ('tipo_opinion', models.CharField(choices=[('Queja', 'Queja'), ('Felicitaciones', 'Felicitaciones'), ('Comentarios', 'Comentarios')], max_length=20, null=True)),
                ('nombre_personal', models.CharField(blank=True, max_length=100, null=True)),
                ('comentarios', models.CharField(max_length=300, null=True)),
                ('creador', models.CharField(blank=True, max_length=90, null=True)),
                ('editor', models.CharField(blank=True, max_length=90, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
                ('Paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Paciente')),
            ],
            options={
                'verbose_name_plural': 'Semin - Paciente Comentarios',
            },
        ),
    ]
