# Generated by Django 2.1.7 on 2020-10-21 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0301_comentarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuejasSugerencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField(blank=True, max_length=40, null=True)),
                ('tipo', models.CharField(choices=[('Queja Interna', 'Queja Interna'), ('Queja Externa', 'Queja Externa'), ('Sugerencia', 'Sugerencia')], max_length=20, null=True)),
                ('fecha_evento', models.DateField(null=True)),
                ('hora_evento', models.TimeField(null=True)),
                ('sucursal', models.CharField(blank=True, max_length=40, null=True)),
                ('tipo_recibo', models.CharField(choices=[('Telefono', 'Telefono'), ('Presencial', 'Presencial'), ('Email', 'Email'), ('Redes Sociales', 'Redes Sociales'), ('Pagina web', 'Pagina web'), ('En Linea', 'En Linea')], max_length=30, null=True)),
                ('nombre_presentante', models.CharField(max_length=100, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(max_length=300, null=True)),
                ('nombre_personal', models.CharField(blank=True, max_length=100, null=True)),
                ('puesto_personal', models.CharField(blank=True, max_length=40, null=True)),
                ('fecha_recibo', models.DateField(blank=True, null=True)),
                ('nombre_encargado', models.CharField(blank=True, max_length=100, null=True)),
                ('puesto_encargado', models.CharField(blank=True, max_length=40, null=True)),
                ('fecha_encargado', models.DateField(blank=True, null=True)),
                ('procede', models.BooleanField(blank=True, null=True)),
                ('recurrente', models.BooleanField(blank=True, null=True)),
                ('creador', models.CharField(blank=True, max_length=90, null=True)),
                ('editor', models.CharField(blank=True, max_length=90, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
                ('Paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Paciente')),
            ],
            options={
                'verbose_name_plural': 'Semin - Paciente Quejas & Sugerencias',
            },
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='hora',
            field=models.TimeField(null=True),
        ),
    ]
