# Generated by Django 2.1.7 on 2020-10-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0302_auto_20201021_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quejassugerencias',
            name='folio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
