# Generated by Django 2.1.7 on 2020-11-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0306_paciente_promocion_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocionticket',
            name='registro',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
