# Generated by Django 2.1.7 on 2020-11-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0307_promocionticket_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='directivo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
