# Generated by Django 2.1.7 on 2020-11-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0308_empleado_directivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quejassugerencias',
            name='procede',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='quejassugerencias',
            name='recurrente',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=3, null=True),
        ),
    ]
