# Generated by Django 2.1.7 on 2020-11-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0310_auto_20201127_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='monedero',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
