# Generated by Django 2.1.7 on 2020-12-10 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0313_auto_20201201_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginClientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(blank=True, choices=[('APP', 'APP'), ('WEB', 'WEB')], max_length=10, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
                ('Paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Paciente')),
            ],
            options={
                'verbose_name_plural': 'Semin - Login Clientes',
            },
        ),
    ]
