# Generated by Django 2.1.7 on 2020-12-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0314_loginclientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='estrellasArray',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
