# Generated by Django 2.1.7 on 2021-01-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0316_auto_20201218_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Medico', 'Medico'), ('Paciente', 'Paciente'), ('Operador', 'Operador'), ('Administrador', 'Administrador'), ('Imagenologia', 'Imagenologia')], max_length=14, null=True),
        ),
    ]
