# Generated by Django 2.1.7 on 2021-02-10 22:14

from django.db import migrations, models
import django.db.models.deletion
import semin.models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0318_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudioEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.IntegerField()),
                ('contraseña', models.IntegerField()),
                ('file', models.FileField(upload_to='estudioEmpresa/', validators=[semin.models.EstudioEmpresa.validate_file])),
                ('categoria', models.CharField(choices=[('Analisis Sanguineos', 'Analisis Sanguineos'), ('Analisis Clinicos', 'Analisis Clinicos'), ('Ultrasonografia', 'Ultrasonografia'), ('Ultrasonografia Doppler', 'Ultrasonografia Doppler'), ('Rayos X', 'Rayos X'), ('Rayos X Contrastados', 'Rayos X Contrastados'), ('Mastografia', 'Mastografia'), ('Papanicolau', 'Papanicolau'), ('Tomografia', 'Tomografia'), ('Tomografia Contrastada', 'Tomografia Contrastada'), ('Resonancia Magnetica', 'Resonancia Magnetica'), ('Resonancia Magnetica Contrastada', 'Resonancia Magnetica Contrastada'), ('Colposcopia', 'Colposcopia'), ('Densitometria', 'Densitometria'), ('Audiologia', 'Audiologia'), ('Espirometria', 'Espirometria'), ('Patologia', 'Patologia'), ('Consulta', 'Consulta'), ('Ginecologia', 'Ginecologia'), ('Cardiologia', 'Cardiologia'), ('Rehabilitacion', 'Rehabilitacion')], max_length=45)),
                ('nombreEstudio', models.CharField(max_length=1000)),
                ('creador', models.CharField(blank=True, max_length=90, null=True)),
                ('editor', models.CharField(blank=True, max_length=90, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
                ('Empresa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='semin.Empresa')),
                ('Paciente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='semin.Paciente')),
            ],
            options={
                'verbose_name_plural': 'Semin - Estudios Empresa',
            },
        ),
    ]
