# Generated by Django 2.1.7 on 2021-02-12 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0320_auto_20210212_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name_plural': 'Empresas - Empresas'},
        ),
        migrations.AlterModelOptions(
            name='estudioempresa',
            options={'verbose_name_plural': 'Empresa - Estudios Empresa'},
        ),
    ]
