# Generated by Django 2.1.7 on 2021-02-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0325_estudioempresa_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudioempresa',
            name='caducidad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
