# Generated by Django 2.1.7 on 2021-03-16 21:00

from django.db import migrations, models
import semin.models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0331_estudioempresa_fecha_realizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rehabilitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePaciente', models.CharField(max_length=90)),
                ('fechaNacimiento', models.DateField(null=True)),
                ('sexo', models.CharField(choices=[('masculino', 'masculino'), ('femenino', 'femenino')], max_length=9, null=True)),
                ('fileHoja', models.FileField(null=True, upload_to='media/rehabilitacion/', validators=[semin.models.Rehabilitacion.validate_file])),
                ('fileConstanciaVigencia', models.FileField(null=True, upload_to='media/rehabilitacion/', validators=[semin.models.Rehabilitacion.validate_file])),
                ('fileOrdenTrabajo', models.FileField(null=True, upload_to='media/rehabilitacion/', validators=[semin.models.Rehabilitacion.validate_file])),
                ('fileIdent', models.FileField(null=True, upload_to='media/rehabilitacion/', validators=[semin.models.Rehabilitacion.validate_file])),
                ('fileCarnet', models.FileField(null=True, upload_to='media/rehabilitacion/', validators=[semin.models.Rehabilitacion.validate_file])),
                ('creador', models.CharField(max_length=90, null=True)),
                ('editor', models.CharField(max_length=90, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Semin - Rehabilitacion - Documentos',
            },
        ),
    ]
