# Generated by Django 2.1.7 on 2021-03-16 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0332_rehabilitacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rehabilitacion',
            options={'verbose_name_plural': 'Rehabilitacion - Documentos'},
        ),
    ]
