# Generated by Django 2.1.7 on 2021-03-17 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0333_auto_20210316_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rehabilitacion',
            old_name='fileCarnet',
            new_name='Carnet',
        ),
        migrations.RenameField(
            model_name='rehabilitacion',
            old_name='fileConstanciaVigencia',
            new_name='ConstanciaVigencia',
        ),
        migrations.RenameField(
            model_name='rehabilitacion',
            old_name='fechaNacimiento',
            new_name='FechaNacimiento',
        ),
        migrations.RenameField(
            model_name='rehabilitacion',
            old_name='fileHoja',
            new_name='Hoja4_30',
        ),
        migrations.RenameField(
            model_name='rehabilitacion',
            old_name='fileIdent',
            new_name='Identificacion',
        ),
        migrations.RenameField(
            model_name='rehabilitacion',
            old_name='nombrePaciente',
            new_name='NombrePaciente',
        ),
        migrations.RenameField(
            model_name='rehabilitacion',
            old_name='fileOrdenTrabajo',
            new_name='OrdenTrabajo',
        ),
        migrations.RenameField(
            model_name='rehabilitacion',
            old_name='sexo',
            new_name='Sexo',
        ),
    ]
