# Generated by Django 2.1.7 on 2021-03-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0334_auto_20210317_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rehabilitacion',
            old_name='Sexo',
            new_name='sexo',
        ),
        migrations.RemoveField(
            model_name='rehabilitacion',
            name='NombrePaciente',
        ),
        migrations.AddField(
            model_name='rehabilitacion',
            name='apellido_materno',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='rehabilitacion',
            name='apellido_paterno',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='rehabilitacion',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rehabilitacion',
            name='FechaNacimiento',
            field=models.DateField(),
        ),
    ]
