# Generated by Django 2.1.7 on 2021-03-17 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0335_auto_20210317_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rehabilitacion',
            old_name='ConstanciaVigencia',
            new_name='Constancia_Vigencia',
        ),
        migrations.RenameField(
            model_name='rehabilitacion',
            old_name='FechaNacimiento',
            new_name='Fecha_Nacimiento',
        ),
        migrations.RenameField(
            model_name='rehabilitacion',
            old_name='Hoja4_30',
            new_name='Hoja_430',
        ),
        migrations.RenameField(
            model_name='rehabilitacion',
            old_name='OrdenTrabajo',
            new_name='Orden_Trabajo',
        ),
    ]
