# Generated by Django 2.1.7 on 2021-03-18 02:21

from django.db import migrations, models
import semin.models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0336_auto_20210317_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehabilitacion',
            name='Carnet',
            field=models.FileField(null=True, upload_to='rehabilitacion/', validators=[semin.models.Rehabilitacion.validate_file]),
        ),
        migrations.AlterField(
            model_name='rehabilitacion',
            name='Constancia_Vigencia',
            field=models.FileField(null=True, upload_to='rehabilitacion/', validators=[semin.models.Rehabilitacion.validate_file]),
        ),
        migrations.AlterField(
            model_name='rehabilitacion',
            name='Hoja_430',
            field=models.FileField(null=True, upload_to='rehabilitacion/', validators=[semin.models.Rehabilitacion.validate_file]),
        ),
        migrations.AlterField(
            model_name='rehabilitacion',
            name='Identificacion',
            field=models.FileField(null=True, upload_to='rehabilitacion/', validators=[semin.models.Rehabilitacion.validate_file]),
        ),
        migrations.AlterField(
            model_name='rehabilitacion',
            name='Orden_Trabajo',
            field=models.FileField(null=True, upload_to='rehabilitacion/', validators=[semin.models.Rehabilitacion.validate_file]),
        ),
    ]
