# Generated by Django 2.1.7 on 2021-03-18 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0337_auto_20210317_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rehabilitacion',
            old_name='Carnet',
            new_name='carnet',
        ),
        migrations.RenameField(
            model_name='rehabilitacion',
            old_name='Constancia_Vigencia',
            new_name='constancia_vigencia',
        ),
        migrations.RenameField(
            model_name='rehabilitacion',
            old_name='Fecha_Nacimiento',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='rehabilitacion',
            old_name='Hoja_430',
            new_name='hoja_430',
        ),
        migrations.RenameField(
            model_name='rehabilitacion',
            old_name='Identificacion',
            new_name='identificacion',
        ),
        migrations.RenameField(
            model_name='rehabilitacion',
            old_name='Orden_Trabajo',
            new_name='orden_trabajo',
        ),
        migrations.RenameField(
            model_name='rehabilitacion',
            old_name='ultimaActualizacion',
            new_name='ultima_actualizacion',
        ),
    ]
