# Generated by Django 2.1.7 on 2021-03-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0339_auto_20210318_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rehabilitacion',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='rehabilitacion',
            name='editor',
        ),
    ]
