# Generated by Django 2.1.7 on 2021-03-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0340_auto_20210319_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name_plural': 'Registro - Fisioterapeuta '},
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='auditor',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='directivo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='editors',
        ),
    ]
