# Generated by Django 2.1.7 on 2021-03-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0342_auto_20210322_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fisioterapeuta',
            options={'verbose_name_plural': 'Registro - Fisioterapeuta'},
        ),
    ]
