# Generated by Django 2.1.7 on 2021-03-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0343_auto_20210322_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapeuta',
            name='puesto',
            field=models.CharField(choices=[('Medico', 'Medico'), ('Paciente', 'Paciente'), ('Operador', 'Operador'), ('Administrador', 'Administrador'), ('Imagenologia', 'Imagenologia'), ('Fisioterapeuta', 'Fisioterapeuta')], max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Medico', 'Medico'), ('Paciente', 'Paciente'), ('Operador', 'Operador'), ('Administrador', 'Administrador'), ('Imagenologia', 'Imagenologia'), ('Fisioterapeuta', 'Fisioterapeuta')], max_length=14, null=True),
        ),
    ]
