# Generated by Django 2.1.7 on 2021-03-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0345_auto_20210322_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fisioterapeuta',
            options={'verbose_name_plural': 'Semin - Fisioterapeuta'},
        ),
    ]
