# Generated by Django 2.1.7 on 2021-03-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0346_auto_20210322_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='FondoLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=90, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='images/login')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Semin - Fondo de Login',
            },
        ),
    ]
