# Generated by Django 2.1.7 on 2021-03-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0349_auto_20210324_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehabilitacion',
            name='status',
            field=models.CharField(choices=[('Correcto', 'Correcto'), ('Incorrecto', 'Incorrecto'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=20, null=True),
        ),
    ]
