# Generated by Django 2.1.7 on 2021-04-07 15:51

from django.db import migrations, models
import semin.models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0351_auto_20210324_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehabilitacion',
            name='acta',
            field=models.FileField(blank=True, null=True, upload_to='rehabilitacion/adultos/', validators=[semin.models.Rehabilitacion.validate_file]),
        ),
        migrations.AddField(
            model_name='rehabilitacion',
            name='curp',
            field=models.FileField(blank=True, null=True, upload_to='rehabilitacion/adultos/', validators=[semin.models.Rehabilitacion.validate_file]),
        ),
    ]
