# Generated by Django 2.1.7 on 2021-04-13 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0352_auto_20210407_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citasucursal',
            name='id_sala',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
