# Generated by Django 2.1.7 on 2021-04-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0353_auto_20210413_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Medico', 'Medico'), ('Paciente', 'Paciente'), ('Operador', 'Operador'), ('Administrador', 'Administrador'), ('Imagenologia', 'Imagenologia'), ('Fisioterapeuta', 'Fisioterapeuta'), ('Almacenista', 'Almacenista')], max_length=14, null=True),
        ),
    ]
