# Generated by Django 2.1.7 on 2021-04-13 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0354_auto_20210413_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90, null=True)),
                ('presentacion', models.CharField(choices=[('pieza', 'pieza'), ('litros', 'litros'), ('paquete', 'paquete'), ('caja', 'caja'), ('kilo', 'kilo')], max_length=40, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_caducidad', models.DateField()),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('stok', models.IntegerField(null=True)),
                ('stok_max', models.IntegerField(null=True)),
                ('stok_min', models.IntegerField(null=True)),
                ('caracteristicas', models.CharField(blank=True, max_length=50, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_compañia', models.CharField(max_length=90, null=True)),
                ('nombre_contacto', models.CharField(max_length=90, null=True)),
                ('apellidoP_contacto', models.CharField(max_length=45, null=True)),
                ('apellidoM_contacto', models.CharField(max_length=45, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=90, null=True)),
                ('email', models.EmailField(blank=True, max_length=45, null=True, unique=True)),
                ('tipo_proveedor', models.CharField(choices=[('primario', 'primario'), ('secundario', 'secundario')], max_length=40, null=True)),
                ('nota', models.CharField(blank=True, max_length=90, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Medico', 'Medico'), ('Paciente', 'Paciente'), ('Operador', 'Operador'), ('Administrador', 'Administrador'), ('Imagenologia', 'Imagenologia'), ('Fisioterapeuta', 'Fisioterapeuta'), ('Almacen', 'Almacen')], max_length=14, null=True),
        ),
    ]
