# Generated by Django 2.1.7 on 2021-04-13 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0355_auto_20210413_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Proveedor'),
        ),
    ]
