# Generated by Django 2.1.7 on 2021-04-13 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0356_productos_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateField()),
                ('nota', models.CharField(blank=True, max_length=150, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
                ('id_produtos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Productos')),
            ],
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nota',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='devoluciones',
            name='id_proveedores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Proveedor'),
        ),
    ]
