# Generated by Django 2.1.7 on 2021-04-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0358_auto_20210413_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devoluciones',
            options={'verbose_name_plural': 'Semin - Devoluciones de Productos'},
        ),
        migrations.AlterModelOptions(
            name='envio',
            options={'verbose_name_plural': 'Semin - Envio de Productos'},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name_plural': 'Semin - Productos Almacen Principal'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Semin - Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name_plural': 'Semin - Solicitud de Productos'},
        ),
    ]
