# Generated by Django 2.1.7 on 2021-04-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0359_auto_20210413_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='ubicacion',
            field=models.CharField(choices=[('toma de muestra', 'toma de muestra'), ('estudio ginecologico', 'estudio ginecologico'), ('imagenologia', 'imagenologia'), ('intendencia', 'intendencia'), ('papeleria', 'papeleria'), ('laboratorio', 'laboratorio')], max_length=40, null=True),
        ),
    ]
