# Generated by Django 2.1.7 on 2021-04-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0360_productos_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoluciones',
            name='motivo',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
