# Generated by Django 2.1.7 on 2021-04-13 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0361_devoluciones_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='envio',
            name='ultimaActualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='ultimaActualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
