# Generated by Django 2.1.7 on 2021-04-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0362_auto_20210413_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_proveedor',
            field=models.CharField(choices=[('primario', 'primario'), ('secundario', 'secundario'), ('otro', 'otro')], max_length=40, null=True),
        ),
    ]
