# Generated by Django 2.1.7 on 2021-04-13 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0363_auto_20210413_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90, null=True)),
                ('id_sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Sucursal')),
            ],
            options={
                'verbose_name_plural': 'Semin - Areas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90, null=True)),
                ('presentacion', models.CharField(choices=[('pieza', 'pieza'), ('litros', 'litros'), ('paquete', 'paquete'), ('caja', 'caja'), ('kilo', 'kilo')], max_length=40, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_caducidad', models.DateField()),
                ('stok', models.IntegerField(null=True)),
                ('stok_max', models.IntegerField(null=True)),
                ('stok_min', models.IntegerField(null=True)),
                ('caracteristicas', models.CharField(blank=True, max_length=50, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Area')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Sucursal')),
            ],
            options={
                'verbose_name_plural': 'Semin - Productos Almacenes',
            },
        ),
    ]
