# Generated by Django 2.1.7 on 2021-04-14 20:42

from django.db import migrations, models
import semin.models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0364_area_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehabilitacion',
            name='bitacora',
            field=models.FileField(blank=True, null=True, upload_to='rehabilitacion/adultos/', validators=[semin.models.Rehabilitacion.validate_file]),
        ),
        migrations.AddField(
            model_name='rehabilitacion',
            name='numero_firmas',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
