# Generated by Django 2.1.7 on 2021-04-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0366_auto_20210414_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180, null=True)),
                ('telefono', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=45, null=True)),
                ('comentario', models.CharField(max_length=500, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Semin - Correos',
            },
        ),
    ]
