# Generated by Django 2.1.7 on 2021-04-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0367_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correo',
            name='comentario',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
