# Generated by Django 2.1.7 on 2021-04-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0368_auto_20210416_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=90, null=True)),
                ('link', models.CharField(max_length=400, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='images/carrousel')),
                ('caducidad', models.DateField(null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Semin - Carrousel',
            },
        ),
    ]
