# Generated by Django 2.1.7 on 2021-04-26 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0370_rehabilitacion_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('edad', models.CharField(blank=True, max_length=50, null=True)),
                ('escolaridad', models.CharField(blank=True, max_length=200, null=True)),
                ('experiencia', models.CharField(blank=True, max_length=200, null=True)),
                ('automovil', models.BooleanField(blank=True, default=False)),
                ('tipo_licencia', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=2000, null=True)),
                ('zona_trabajo', models.CharField(blank=True, max_length=200, null=True)),
                ('requerimientos', models.CharField(blank=True, max_length=2000, null=True)),
                ('fecha_contratacion', models.DateField(blank=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'RH - Bolsa de trabajo',
            },
        ),
        migrations.CreateModel(
            name='Bolsa_Conocimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conocimiento', models.CharField(blank=True, max_length=400, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'RH - Conocimientos',
            },
        ),
        migrations.AddField(
            model_name='bolsa',
            name='Bolsa_Conocimientos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Bolsa_Conocimientos'),
        ),
    ]
