# Generated by Django 2.1.7 on 2021-04-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0371_auto_20210426_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsa',
            name='automovil',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='descripcion',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='edad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='escolaridad',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='experiencia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='fecha_contratacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='requerimientos',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='tipo_licencia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='titulo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='zona_trabajo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
