# Generated by Django 2.1.7 on 2021-04-26 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0377_auto_20210426_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolsa_conocimientos',
            name='Bolsa',
        ),
        migrations.AddField(
            model_name='bolsa',
            name='Bolsa_Conocimientos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Bolsa_Conocimientos'),
        ),
    ]
