# Generated by Django 2.1.7 on 2021-04-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0378_auto_20210426_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolsa',
            name='Bolsa_Conocimientos',
        ),
        migrations.AddField(
            model_name='bolsa',
            name='conocimiento_cinco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='conocimiento_cuatro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='conocimiento_diez',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='conocimiento_dos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='conocimiento_nueve',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='conocimiento_ocho',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='conocimiento_seis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='conocimiento_siete',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='conocimiento_tres',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='conocimiento_uno',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Bolsa_Conocimientos',
        ),
    ]
