# Generated by Django 2.1.7 on 2021-04-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0379_auto_20210426_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsa',
            name='conocimiento_uno',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
