# Generated by Django 2.1.7 on 2021-04-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0380_auto_20210426_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsa',
            name='salario',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
