# Generated by Django 2.1.7 on 2021-04-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0381_bolsa_salario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bolsa',
            old_name='requerimientos',
            new_name='actividades',
        ),
        migrations.AddField(
            model_name='bolsa',
            name='disp_residencia',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='disp_viajar',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'masculino'), ('femenino', 'femenino'), ('indistinto', 'indistinto')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='tipo_licencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
