# Generated by Django 2.1.7 on 2021-04-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0382_auto_20210426_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsa',
            name='funciones_cinco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='funciones_cuatro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='funciones_diez',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='funciones_dos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='funciones_nueve',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='funciones_ocho',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='funciones_seis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='funciones_siete',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='funciones_tres',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='funciones_uno',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='disp_viajar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
