# Generated by Django 2.1.7 on 2021-04-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0384_auto_20210427_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='curp',
            new_name='curpo',
        ),
    ]
