# Generated by Django 2.1.7 on 2021-04-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0385_auto_20210429_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='curpo',
            new_name='curp',
        ),
    ]
