# Generated by Django 2.1.7 on 2021-04-29 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0386_auto_20210429_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='telefonoCasa',
            new_name='telefonoCasa2',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='telefonoCelular',
            new_name='telefonoCelular2',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='telefonoOficina',
            new_name='telefonoOficina2',
        ),
    ]
