# Generated by Django 2.1.7 on 2021-04-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0387_auto_20210429_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='telefonoCasa2',
            new_name='telefonoCasa',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='telefonoCelular2',
            new_name='telefonoCelular',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='telefonoOficina2',
            new_name='telefonoOficina',
        ),
    ]
