# Generated by Django 2.1.7 on 2021-05-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0389_promocionticket_prueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Paciente', 'Paciente'), ('Operador', 'Operador'), ('Imagenologia', 'Imagenologia'), ('Fisioterapeuta', 'Fisioterapeuta'), ('Almacen', 'Almacen'), ('Medico', 'Medico'), ('Administrador', 'Administrador'), ('administrador_editor', 'administrador_editor'), ('administrador_titular', 'administrador_titular')], max_length=14, null=True),
        ),
    ]
