# Generated by Django 2.1.7 on 2021-05-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0390_auto_20210510_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='ExLab',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadservicio',
            name='ExRx',
            field=models.IntegerField(default=0),
        ),
    ]
