# Generated by Django 2.1.7 on 2021-05-14 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0392_sensortemperatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90, null=True)),
                ('apellido_paterno', models.CharField(max_length=45, null=True)),
                ('apellido_materno', models.CharField(max_length=45, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('sexo', models.CharField(choices=[('masculino', 'masculino'), ('femenino', 'femenino')], max_length=9, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=45, null=True, unique=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Semin - Mensajeros',
            },
        ),
        migrations.AlterModelOptions(
            name='sensortemperatura',
            options={'verbose_name_plural': 'Semin - Temepraturas'},
        ),
        migrations.AddField(
            model_name='sensortemperatura',
            name='identificador',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='sensortemperatura',
            name='mensajero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semin.Mensajero'),
        ),
    ]
