# Generated by Django 2.1.7 on 2021-05-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0393_auto_20210514_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensortemperatura',
            options={'verbose_name_plural': 'Semin - Temperaturas'},
        ),
    ]
