# Generated by Django 2.1.7 on 2021-05-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0395_auto_20210525_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturacion',
            old_name='aprovado',
            new_name='aprobado',
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='factura_estatus',
            field=models.CharField(choices=[('SOLICITADO', 'SOLICITADO'), ('CORREGIDO', 'CORREGIDO'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO'), ('CANCELADO', 'CANCELADO')], max_length=10, null=True),
        ),
    ]
