# Generated by Django 2.1.7 on 2021-05-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0396_auto_20210528_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callcenter',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='callcenter',
            name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='callcenter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='callcenter',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='callcenter',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='callcenter',
            name='interes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='callcenter',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
