# Generated by Django 2.1.7 on 2021-06-07 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('semin', '0398_almacenista_jefesucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacenista',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='almacenista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jefesucursal',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='jefeSucursal', to=settings.AUTH_USER_MODEL),
        ),
    ]
