# Generated by Django 2.1.7 on 2021-06-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0401_auto_20210615_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Paciente', 'Paciente'), ('Operador', 'Operador'), ('Imagenologia', 'Imagenologia'), ('Fisioterapeuta', 'Fisioterapeuta'), ('Almacenista', 'Almacenista'), ('Medico', 'Medico'), ('Administrador', 'Administrador'), ('panel_data', 'panel_data'), ('administrador_editor', 'administrador_editor'), ('administrador_titular', 'administrador_titular')], max_length=14, null=True),
        ),
    ]
