# Generated by Django 2.1.7 on 2021-07-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0402_auto_20210629_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Paciente', 'Paciente'), ('Operador', 'Operador'), ('Imagenologia', 'Imagenologia'), ('Fisioterapeuta', 'Fisioterapeuta'), ('Almacenista', 'Almacenista'), ('Medico', 'Medico'), ('Administrador', 'Administrador'), ('Admin_panel_data', 'Admin_panel_data'), ('Auditor_panel_data', 'Auditor_panel_data'), ('administrador_editor', 'administrador_editor'), ('administrador_titular', 'administrador_titular')], max_length=14, null=True),
        ),
    ]
