export interface DisponibilidadInterface{
    id?: string;
    Cons_1?: string;
    Cons_2?: string;
    US_1?: string;
    US_2?: string;
    RXS_1?: string;
    RXS_2?: string;
    RXC_1?: string;
    RXC_2?: string;
    Masto_1?: string;
    Masto_2?: string;
    ConsReha?: any;
    EKG_1?: string;
    EKG_2?: string;
    TAC_1?: string;
    TAC_2?: string;
    RM_1?: string;
    RM_2?: string;
    Colpo_1?: string;
    Colpo_2?: string;
    Densi_1?: string;
    Densi_2?: string;
    Cli_1?: string;
    Cli_2?: string;
    Cli_3?: string;
    Cli_4?: string;
    Cli_5?: string;
    Cli_6?: string;
    Cli_7?: string;
    Sucursal?: any;
    /*Add to prodcution*/
    RX ?: any;
    RM  ?: any;
    Colpo ?: any ;
    Masto ?: any;
    TAC ?: any ;
    Papa ?: any ;
    Densi ?: any ;
    Sang ?: any ;
    Esp ?: any ;
    US ?: any ;
    RXS ?: any ;
    RXC ?: any ;
    EKG ?: any ;
    Inc1 ?: any ;
    Inc2 ?: any ;
    Exp1 ?: any ;
    Hab1 ?: any ;
    Hab2 ?: any ;
    Hab3 ?: any ;
    Hab4 ?: any ;
    Hab5 ?: any ;
    Hab6 ?: any ;
    Hab7 ?: any ;
    Quir1 ?: any ;
    Quir2 ?: any ;
    ConsGineco ?: any ;
    Cons1 ?: any ;
    Cons2 ?: any ;
    Pato ?: any ;
    Card ?: any ;
    results ?: any;
    count ?: any; 
    RehaEle1 ?: any;
    RehaEle2 ?: any;
    RehaEle3 ?: any;
    RehaEle4 ?: any;
    RehaEle5 ?: any;
    RehaEle6 ?: any;
    RehaEle7 ?: any;
    RehaEle8 ?: any;
    RehaHid1 ?: any;
    RehaMec1 ?: any;
    ConsFis1 ?: any;
    ConsFis2 ?: any;
    ConsFis3 ?: any;
    ConsPed ?: any;
    ServDom1 ?: any;
    ServDom2 ?: any;
    ServDomRx ?: any;
    Audio ?: any;
    Covid ?: any;
    Covid2 ?: any;
}
